# Generated by cloudcoil-model-codegen v0.7.1
# DO NOT EDIT

from typing import (
    Annotated,
    Any,
    Callable,
    ClassVar,
    Literal,
    overload,
)

from cloudcoil.apimachinery import ObjectMeta
from cloudcoil.pydantic import (
    UNSET,
    BaseModel,
    BaseModelBuilder,
    BuilderContextBase,
    GenericListBuilder,
    ListBuilderContext,
    Never,
    Self,
)
from cloudcoil.resources import Resource
from pydantic import Field


class IntegrationSourceSpecCeOverrides(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSourceSpecCeOverrides"]:
            return IntegrationSourceSpecCeOverrides

        def build(self) -> "IntegrationSourceSpecCeOverrides":
            return IntegrationSourceSpecCeOverrides(**self._attrs)

        def extensions(self, value: dict[str, Any] | None, /) -> Self:
            "Extensions specify what attribute are added or overridden on the outbound event. Each `Extensions` key-value pair are set on the event as an attribute extension independently."
            return self._set("extensions", value)

    class BuilderContext(BuilderContextBase["IntegrationSourceSpecCeOverrides.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSourceSpecCeOverrides.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSourceSpecCeOverrides."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["IntegrationSourceSpecCeOverrides", Builder]:
        return GenericListBuilder[
            IntegrationSourceSpecCeOverrides, IntegrationSourceSpecCeOverrides.Builder
        ]()

    extensions: dict[str, Any] | None = None
    "Extensions specify what attribute are added or overridden on the outbound event. Each `Extensions` key-value pair are set on the event as an attribute extension independently."


class IntegrationSourceSpecSinkRef(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSourceSpecSinkRef"]:
            return IntegrationSourceSpecSinkRef

        def build(self) -> "IntegrationSourceSpecSinkRef":
            return IntegrationSourceSpecSinkRef(**self._attrs)

        def api_version(self, value: str | None, /) -> Self:
            "API version of the referent."
            return self._set("api_version", value)

        def kind(self, value: str | None, /) -> Self:
            "Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        def name(self, value: str | None, /) -> Self:
            "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
            return self._set("name", value)

        def namespace(self, value: str | None, /) -> Self:
            "Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/ This is optional field, it gets defaulted to the object holding it if left out."
            return self._set("namespace", value)

    class BuilderContext(BuilderContextBase["IntegrationSourceSpecSinkRef.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSourceSpecSinkRef.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSourceSpecSinkRef."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["IntegrationSourceSpecSinkRef", Builder]:
        return GenericListBuilder[
            IntegrationSourceSpecSinkRef, IntegrationSourceSpecSinkRef.Builder
        ]()

    api_version: Annotated[str | None, Field(alias="apiVersion")] = None
    "API version of the referent."
    kind: str | None = None
    "Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    name: str | None = None
    "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
    namespace: str | None = None
    "Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/ This is optional field, it gets defaulted to the object holding it if left out."


class IntegrationSourceSpecTimer(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSourceSpecTimer"]:
            return IntegrationSourceSpecTimer

        def build(self) -> "IntegrationSourceSpecTimer":
            return IntegrationSourceSpecTimer(**self._attrs)

        def period(self, value: int | None, /) -> Self:
            "The interval (in milliseconds) to wait between producing the next message."
            return self._set("period", value)

        def message(self, value: str | None, /) -> Self:
            "The message to generate."
            return self._set("message", value)

        def content_type(self, value: str | None, /) -> Self:
            "The content type of the generated message."
            return self._set("content_type", value)

        def repeat_count(self, value: int | None, /) -> Self:
            "Specifies a maximum limit of number of fires"
            return self._set("repeat_count", value)

    class BuilderContext(BuilderContextBase["IntegrationSourceSpecTimer.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSourceSpecTimer.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSourceSpecTimer."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["IntegrationSourceSpecTimer", Builder]:
        return GenericListBuilder[IntegrationSourceSpecTimer, IntegrationSourceSpecTimer.Builder]()

    period: Annotated[int | None, Field(title="Period")] = 1000
    "The interval (in milliseconds) to wait between producing the next message."
    message: Annotated[str | None, Field(examples=["hello world"], title="Message")] = None
    "The message to generate."
    content_type: Annotated[str | None, Field(alias="contentType", title="Content Type")] = (
        "text/plain"
    )
    "The content type of the generated message."
    repeat_count: Annotated[int | None, Field(alias="repeatCount", title="Repeat Count")] = None
    "Specifies a maximum limit of number of fires"


class IntegrationSourceSpecAwsS3(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSourceSpecAwsS3"]:
            return IntegrationSourceSpecAwsS3

        def build(self) -> "IntegrationSourceSpecAwsS3":
            return IntegrationSourceSpecAwsS3(**self._attrs)

        def arn(self, value: str | None, /) -> Self:
            "The S3 Bucket name or Amazon Resource Name (ARN)."
            return self._set("arn", value)

        def delete_after_read(self, value: bool | None, /) -> Self:
            "Specifies to delete objects after consuming them."
            return self._set("delete_after_read", value)

        def move_after_read(self, value: bool | None, /) -> Self:
            "Move objects from S3 bucket to a different bucket after they have been retrieved."
            return self._set("move_after_read", value)

        def destination_bucket(self, value: str | None, /) -> Self:
            "Define the destination bucket where an object must be moved when moveAfterRead is set to true."
            return self._set("destination_bucket", value)

        def destination_bucket_prefix(self, value: str | None, /) -> Self:
            "Define the destination bucket prefix to use when an object must be moved, and moveAfterRead is set to true."
            return self._set("destination_bucket_prefix", value)

        def destination_bucket_suffix(self, value: str | None, /) -> Self:
            "Define the destination bucket suffix to use when an object must be moved, and moveAfterRead is set to true."
            return self._set("destination_bucket_suffix", value)

        def region(self, value: str | None, /) -> Self:
            "The AWS region to access."
            return self._set("region", value)

        def auto_create_bucket(self, value: bool | None, /) -> Self:
            "Specifies to automatically create the S3 bucket."
            return self._set("auto_create_bucket", value)

        def prefix(self, value: str | None, /) -> Self:
            "The AWS S3 bucket prefix to consider while searching."
            return self._set("prefix", value)

        def ignore_body(self, value: bool | None, /) -> Self:
            "If true, the S3 Object body is ignored. Setting this to true overrides any behavior defined by the `includeBody` option. If false, the S3 object is put in the body."
            return self._set("ignore_body", value)

        def uri_endpoint_override(self, value: str | None, /) -> Self:
            "The overriding endpoint URI. To use this option, you must also select the `overrideEndpoint` option."
            return self._set("uri_endpoint_override", value)

        def override_endpoint(self, value: bool | None, /) -> Self:
            "Select this option to override the endpoint URI. To use this option, you must also provide a URI for the `uriEndpointOverride` option."
            return self._set("override_endpoint", value)

        def force_path_style(self, value: bool | None, /) -> Self:
            "Forces path style when accessing AWS S3 buckets."
            return self._set("force_path_style", value)

        def delay(self, value: int | None, /) -> Self:
            "The number of milliseconds before the next poll of the selected bucket."
            return self._set("delay", value)

        def max_messages_per_poll(self, value: int | None, /) -> Self:
            "Gets the maximum number of messages as a limit to poll at each polling. Gets the maximum number of messages as a limit to poll at each polling. The default value is 10. Use 0 or a negative number to set it as unlimited."
            return self._set("max_messages_per_poll", value)

    class BuilderContext(BuilderContextBase["IntegrationSourceSpecAwsS3.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSourceSpecAwsS3.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSourceSpecAwsS3."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["IntegrationSourceSpecAwsS3", Builder]:
        return GenericListBuilder[IntegrationSourceSpecAwsS3, IntegrationSourceSpecAwsS3.Builder]()

    arn: Annotated[str | None, Field(title="Bucket Name")] = None
    "The S3 Bucket name or Amazon Resource Name (ARN)."
    delete_after_read: Annotated[
        bool | None, Field(alias="deleteAfterRead", title="Auto-delete Objects")
    ] = True
    "Specifies to delete objects after consuming them."
    move_after_read: Annotated[
        bool | None, Field(alias="moveAfterRead", title="Move Objects After Delete")
    ] = False
    "Move objects from S3 bucket to a different bucket after they have been retrieved."
    destination_bucket: Annotated[
        str | None, Field(alias="destinationBucket", title="Destination Bucket")
    ] = None
    "Define the destination bucket where an object must be moved when moveAfterRead is set to true."
    destination_bucket_prefix: Annotated[
        str | None,
        Field(alias="destinationBucketPrefix", title="Destination Bucket Prefix"),
    ] = None
    "Define the destination bucket prefix to use when an object must be moved, and moveAfterRead is set to true."
    destination_bucket_suffix: Annotated[
        str | None,
        Field(alias="destinationBucketSuffix", title="Destination Bucket Suffix"),
    ] = None
    "Define the destination bucket suffix to use when an object must be moved, and moveAfterRead is set to true."
    region: Annotated[str | None, Field(title="AWS Region")] = None
    "The AWS region to access."
    auto_create_bucket: Annotated[
        bool | None, Field(alias="autoCreateBucket", title="Autocreate Bucket")
    ] = False
    "Specifies to automatically create the S3 bucket."
    prefix: Annotated[str | None, Field(examples=["folder/"], title="Prefix")] = None
    "The AWS S3 bucket prefix to consider while searching."
    ignore_body: Annotated[bool | None, Field(alias="ignoreBody", title="Ignore Body")] = False
    "If true, the S3 Object body is ignored. Setting this to true overrides any behavior defined by the `includeBody` option. If false, the S3 object is put in the body."
    uri_endpoint_override: Annotated[
        str | None, Field(alias="uriEndpointOverride", title="Overwrite Endpoint URI")
    ] = None
    "The overriding endpoint URI. To use this option, you must also select the `overrideEndpoint` option."
    override_endpoint: Annotated[
        bool | None, Field(alias="overrideEndpoint", title="Endpoint Overwrite")
    ] = False
    "Select this option to override the endpoint URI. To use this option, you must also provide a URI for the `uriEndpointOverride` option."
    force_path_style: Annotated[
        bool | None, Field(alias="forcePathStyle", title="Force Path Style")
    ] = False
    "Forces path style when accessing AWS S3 buckets."
    delay: Annotated[int | None, Field(title="Delay")] = 500
    "The number of milliseconds before the next poll of the selected bucket."
    max_messages_per_poll: Annotated[
        int | None, Field(alias="maxMessagesPerPoll", title="Max Messages Per Poll")
    ] = 10
    "Gets the maximum number of messages as a limit to poll at each polling. Gets the maximum number of messages as a limit to poll at each polling. The default value is 10. Use 0 or a negative number to set it as unlimited."


class IntegrationSourceSpecAwsSqs(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSourceSpecAwsSqs"]:
            return IntegrationSourceSpecAwsSqs

        def build(self) -> "IntegrationSourceSpecAwsSqs":
            return IntegrationSourceSpecAwsSqs(**self._attrs)

        def arn(self, value: str | None, /) -> Self:
            "The SQS Queue Name or ARN"
            return self._set("arn", value)

        def delete_after_read(self, value: bool | None, /) -> Self:
            "Delete messages after consuming them"
            return self._set("delete_after_read", value)

        def region(self, value: str | None, /) -> Self:
            "The AWS region to access."
            return self._set("region", value)

        def auto_create_queue(self, value: bool | None, /) -> Self:
            "Setting the autocreation of the SQS queue."
            return self._set("auto_create_queue", value)

        def host(self, value: str | None, /) -> Self:
            "The hostname of the Amazon AWS cloud."
            return self._set("host", value)

        def protocol(self, value: str | None, /) -> Self:
            "The underlying protocol used to communicate with SQS"
            return self._set("protocol", value)

        def queue_url(self, value: str | None, /) -> Self:
            "The full SQS Queue URL (required if using KEDA)"
            return self._set("queue_url", value)

        def uri_endpoint_override(self, value: str | None, /) -> Self:
            "The overriding endpoint URI. To use this option, you must also select the `overrideEndpoint` option."
            return self._set("uri_endpoint_override", value)

        def override_endpoint(self, value: bool | None, /) -> Self:
            "Select this option to override the endpoint URI. To use this option, you must also provide a URI for the `uriEndpointOverride` option."
            return self._set("override_endpoint", value)

        def delay(self, value: int | None, /) -> Self:
            "The number of milliseconds before the next poll of the selected stream"
            return self._set("delay", value)

        def greedy(self, value: bool | None, /) -> Self:
            "If greedy is enabled, then the polling will happen immediately again, if the previous run polled 1 or more messages."
            return self._set("greedy", value)

        def max_messages_per_poll(self, value: int | None, /) -> Self:
            "The maximum number of messages to return. Amazon SQS never returns more messages than this value (however, fewer messages might be returned). Valid values 1 to 10. Default 1."
            return self._set("max_messages_per_poll", value)

        def wait_time_seconds(self, value: int | None, /) -> Self:
            "The duration (in seconds) for which the call waits for a message to arrive in the queue before returning. If a message is available, the call returns sooner than WaitTimeSeconds. If no messages are available and the wait time expires, the call does not return a message list."
            return self._set("wait_time_seconds", value)

        def visibility_timeout(self, value: int | None, /) -> Self:
            "The duration (in seconds) that the received messages are hidden from subsequent retrieve requests after being retrieved by a ReceiveMessage request."
            return self._set("visibility_timeout", value)

    class BuilderContext(BuilderContextBase["IntegrationSourceSpecAwsSqs.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSourceSpecAwsSqs.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSourceSpecAwsSqs."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["IntegrationSourceSpecAwsSqs", Builder]:
        return GenericListBuilder[
            IntegrationSourceSpecAwsSqs, IntegrationSourceSpecAwsSqs.Builder
        ]()

    arn: Annotated[str | None, Field(title="Queue Name")] = None
    "The SQS Queue Name or ARN"
    delete_after_read: Annotated[
        bool | None, Field(alias="deleteAfterRead", title="Auto-delete Messages")
    ] = True
    "Delete messages after consuming them"
    region: Annotated[str | None, Field(title="AWS Region")] = None
    "The AWS region to access."
    auto_create_queue: Annotated[
        bool | None, Field(alias="autoCreateQueue", title="Autocreate Queue")
    ] = False
    "Setting the autocreation of the SQS queue."
    host: Annotated[str | None, Field(title="AWS Host")] = "amazonaws.com"
    "The hostname of the Amazon AWS cloud."
    protocol: Annotated[str | None, Field(examples=["http or https"], title="Protocol")] = "https"
    "The underlying protocol used to communicate with SQS"
    queue_url: Annotated[str | None, Field(alias="queueURL", title="Queue URL")] = None
    "The full SQS Queue URL (required if using KEDA)"
    uri_endpoint_override: Annotated[
        str | None, Field(alias="uriEndpointOverride", title="Overwrite Endpoint URI")
    ] = None
    "The overriding endpoint URI. To use this option, you must also select the `overrideEndpoint` option."
    override_endpoint: Annotated[
        bool | None, Field(alias="overrideEndpoint", title="Endpoint Overwrite")
    ] = False
    "Select this option to override the endpoint URI. To use this option, you must also provide a URI for the `uriEndpointOverride` option."
    delay: Annotated[int | None, Field(title="Delay")] = 500
    "The number of milliseconds before the next poll of the selected stream"
    greedy: Annotated[bool | None, Field(title="Greedy Scheduler")] = False
    "If greedy is enabled, then the polling will happen immediately again, if the previous run polled 1 or more messages."
    max_messages_per_poll: Annotated[
        int | None, Field(alias="maxMessagesPerPoll", title="Max Messages Per Poll")
    ] = 1
    "The maximum number of messages to return. Amazon SQS never returns more messages than this value (however, fewer messages might be returned). Valid values 1 to 10. Default 1."
    wait_time_seconds: Annotated[
        int | None, Field(alias="waitTimeSeconds", title="Wait Time Seconds")
    ] = None
    "The duration (in seconds) for which the call waits for a message to arrive in the queue before returning. If a message is available, the call returns sooner than WaitTimeSeconds. If no messages are available and the wait time expires, the call does not return a message list."
    visibility_timeout: Annotated[
        int | None, Field(alias="visibilityTimeout", title="Visibility Timeout")
    ] = None
    "The duration (in seconds) that the received messages are hidden from subsequent retrieve requests after being retrieved by a ReceiveMessage request."


class IntegrationSourceSpecAwsDdbStreams(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSourceSpecAwsDdbStreams"]:
            return IntegrationSourceSpecAwsDdbStreams

        def build(self) -> "IntegrationSourceSpecAwsDdbStreams":
            return IntegrationSourceSpecAwsDdbStreams(**self._attrs)

        def table(self, value: str | None, /) -> Self:
            "The name of the DynamoDB table."
            return self._set("table", value)

        def region(self, value: str | None, /) -> Self:
            "The AWS region to access."
            return self._set("region", value)

        def stream_iterator_type(self, value: str | None, /) -> Self:
            "Defines where in the DynamoDB stream to start getting records. There are two enums and the value can be one of FROM_LATEST and FROM_START. Note that using FROM_START can cause a significant delay before the stream has caught up to real-time."
            return self._set("stream_iterator_type", value)

        def uri_endpoint_override(self, value: str | None, /) -> Self:
            "The overriding endpoint URI. To use this option, you must also select the `overrideEndpoint` option."
            return self._set("uri_endpoint_override", value)

        def override_endpoint(self, value: bool | None, /) -> Self:
            "Select this option to override the endpoint URI. To use this option, you must also provide a URI for the `uriEndpointOverride` option."
            return self._set("override_endpoint", value)

        def delay(self, value: int | None, /) -> Self:
            "The number of milliseconds before the next poll from the database."
            return self._set("delay", value)

    class BuilderContext(BuilderContextBase["IntegrationSourceSpecAwsDdbStreams.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSourceSpecAwsDdbStreams.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSourceSpecAwsDdbStreams."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["IntegrationSourceSpecAwsDdbStreams", Builder]:
        return GenericListBuilder[
            IntegrationSourceSpecAwsDdbStreams,
            IntegrationSourceSpecAwsDdbStreams.Builder,
        ]()

    table: Annotated[str | None, Field(title="Table")] = None
    "The name of the DynamoDB table."
    region: Annotated[str | None, Field(title="AWS Region")] = None
    "The AWS region to access."
    stream_iterator_type: Annotated[
        str | None, Field(alias="streamIteratorType", title="Stream Iterator Type")
    ] = "FROM_LATEST"
    "Defines where in the DynamoDB stream to start getting records. There are two enums and the value can be one of FROM_LATEST and FROM_START. Note that using FROM_START can cause a significant delay before the stream has caught up to real-time."
    uri_endpoint_override: Annotated[
        str | None, Field(alias="uriEndpointOverride", title="Overwrite Endpoint URI")
    ] = None
    "The overriding endpoint URI. To use this option, you must also select the `overrideEndpoint` option."
    override_endpoint: Annotated[
        bool | None, Field(alias="overrideEndpoint", title="Endpoint Overwrite")
    ] = False
    "Select this option to override the endpoint URI. To use this option, you must also provide a URI for the `uriEndpointOverride` option."
    delay: Annotated[int | None, Field(title="Delay")] = 500
    "The number of milliseconds before the next poll from the database."


class IntegrationSourceSpecAwsAuthSecretRef(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSourceSpecAwsAuthSecretRef"]:
            return IntegrationSourceSpecAwsAuthSecretRef

        def build(self) -> "IntegrationSourceSpecAwsAuthSecretRef":
            return IntegrationSourceSpecAwsAuthSecretRef(**self._attrs)

        def name(self, value: str, /) -> Self:
            "Secret name"
            return self._set("name", value)

    class BuilderContext(BuilderContextBase["IntegrationSourceSpecAwsAuthSecretRef.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSourceSpecAwsAuthSecretRef.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSourceSpecAwsAuthSecretRef."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["IntegrationSourceSpecAwsAuthSecretRef", Builder]:
        return GenericListBuilder[
            IntegrationSourceSpecAwsAuthSecretRef,
            IntegrationSourceSpecAwsAuthSecretRef.Builder,
        ]()

    name: str
    "Secret name"


class IntegrationSourceStatusAuth(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSourceStatusAuth"]:
            return IntegrationSourceStatusAuth

        def build(self) -> "IntegrationSourceStatusAuth":
            return IntegrationSourceStatusAuth(**self._attrs)

        def service_account_name(self, value: str | None, /) -> Self:
            "ServiceAccountName is the name of the generated service account used for this components OIDC authentication."
            return self._set("service_account_name", value)

        def service_account_names(self, value: list[str] | None, /) -> Self:
            "ServiceAccountNames is the list of names of the generated service accounts used for this components OIDC authentication."
            return self._set("service_account_names", value)

    class BuilderContext(BuilderContextBase["IntegrationSourceStatusAuth.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSourceStatusAuth.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSourceStatusAuth."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["IntegrationSourceStatusAuth", Builder]:
        return GenericListBuilder[
            IntegrationSourceStatusAuth, IntegrationSourceStatusAuth.Builder
        ]()

    service_account_name: Annotated[str | None, Field(alias="serviceAccountName")] = None
    "ServiceAccountName is the name of the generated service account used for this components OIDC authentication."
    service_account_names: Annotated[list[str] | None, Field(alias="serviceAccountNames")] = None
    "ServiceAccountNames is the list of names of the generated service accounts used for this components OIDC authentication."


class IntegrationSourceStatusCeAttributesItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSourceStatusCeAttributesItem"]:
            return IntegrationSourceStatusCeAttributesItem

        def build(self) -> "IntegrationSourceStatusCeAttributesItem":
            return IntegrationSourceStatusCeAttributesItem(**self._attrs)

        def source(self, value: str | None, /) -> Self:
            "Source is the CloudEvents source attribute."
            return self._set("source", value)

        def type(self, value: str | None, /) -> Self:
            "Type refers to the CloudEvent type attribute."
            return self._set("type", value)

    class BuilderContext(BuilderContextBase["IntegrationSourceStatusCeAttributesItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSourceStatusCeAttributesItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSourceStatusCeAttributesItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["IntegrationSourceStatusCeAttributesItem", Builder]:
        return GenericListBuilder[
            IntegrationSourceStatusCeAttributesItem,
            IntegrationSourceStatusCeAttributesItem.Builder,
        ]()

    source: str | None = None
    "Source is the CloudEvents source attribute."
    type: str | None = None
    "Type refers to the CloudEvent type attribute."


class IntegrationSourceStatusConditionsItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSourceStatusConditionsItem"]:
            return IntegrationSourceStatusConditionsItem

        def build(self) -> "IntegrationSourceStatusConditionsItem":
            return IntegrationSourceStatusConditionsItem(**self._attrs)

        def last_transition_time(self, value: str | None, /) -> Self:
            "LastTransitionTime is the last time the condition transitioned from one status to another. We use VolatileTime in place of metav1.Time to exclude this from creating equality.Semantic differences (all other things held constant)."
            return self._set("last_transition_time", value)

        def message(self, value: str | None, /) -> Self:
            "A human readable message indicating details about the transition."
            return self._set("message", value)

        def reason(self, value: str | None, /) -> Self:
            "The reason for the condition\u0027s last transition."
            return self._set("reason", value)

        def severity(self, value: str | None, /) -> Self:
            "Severity with which to treat failures of this type of condition. When this is not specified, it defaults to Error."
            return self._set("severity", value)

        def status(self, value: str, /) -> Self:
            "Status of the condition, one of True, False, Unknown."
            return self._set("status", value)

        def type(self, value: str, /) -> Self:
            "Type of condition."
            return self._set("type", value)

    class BuilderContext(BuilderContextBase["IntegrationSourceStatusConditionsItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSourceStatusConditionsItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSourceStatusConditionsItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["IntegrationSourceStatusConditionsItem", Builder]:
        return GenericListBuilder[
            IntegrationSourceStatusConditionsItem,
            IntegrationSourceStatusConditionsItem.Builder,
        ]()

    last_transition_time: Annotated[str | None, Field(alias="lastTransitionTime")] = None
    "LastTransitionTime is the last time the condition transitioned from one status to another. We use VolatileTime in place of metav1.Time to exclude this from creating equality.Semantic differences (all other things held constant)."
    message: str | None = None
    "A human readable message indicating details about the transition."
    reason: str | None = None
    "The reason for the condition\u0027s last transition."
    severity: str | None = None
    "Severity with which to treat failures of this type of condition. When this is not specified, it defaults to Error."
    status: str
    "Status of the condition, one of True, False, Unknown."
    type: str
    "Type of condition."


class IntegrationSourceStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSourceStatus"]:
            return IntegrationSourceStatus

        def build(self) -> "IntegrationSourceStatus":
            return IntegrationSourceStatus(**self._attrs)

        def annotations(self, value: dict[str, Any] | None, /) -> Self:
            "Annotations is additional Status fields for the Resource to save some additional State as well as convey more information to the user. This is roughly akin to Annotations on any k8s resource, just the reconciler conveying richer information outwards."
            return self._set("annotations", value)

        @overload
        def auth(
            self, value_or_callback: IntegrationSourceStatusAuth | None, /
        ) -> "IntegrationSourceStatus.Builder": ...

        @overload
        def auth(
            self,
            value_or_callback: Callable[
                [IntegrationSourceStatusAuth.Builder],
                IntegrationSourceStatusAuth.Builder | IntegrationSourceStatusAuth,
            ],
            /,
        ) -> "IntegrationSourceStatus.Builder": ...

        @overload
        def auth(
            self, value_or_callback: Never = ...
        ) -> "IntegrationSourceStatusAuth.BuilderContext": ...

        def auth(self, value_or_callback=UNSET, /):
            "Auth provides the relevant information for OIDC authentication."
            if self._in_context and value_or_callback is UNSET:
                context = IntegrationSourceStatusAuth.BuilderContext()
                context._parent_builder = self
                context._field_name = "auth"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntegrationSourceStatusAuth.builder())
                if isinstance(output, IntegrationSourceStatusAuth.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("auth", value)

        @overload
        def ce_attributes(
            self,
            value_or_callback: list[IntegrationSourceStatusCeAttributesItem] | None,
            /,
        ) -> "IntegrationSourceStatus.Builder": ...

        @overload
        def ce_attributes(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        IntegrationSourceStatusCeAttributesItem,
                        IntegrationSourceStatusCeAttributesItem.Builder,
                    ]
                ],
                GenericListBuilder[
                    IntegrationSourceStatusCeAttributesItem,
                    IntegrationSourceStatusCeAttributesItem.Builder,
                ]
                | list[IntegrationSourceStatusCeAttributesItem],
            ],
            /,
        ) -> "IntegrationSourceStatus.Builder": ...

        @overload
        def ce_attributes(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[IntegrationSourceStatusCeAttributesItem.Builder]: ...

        def ce_attributes(self, value_or_callback=UNSET, /):
            "CloudEventAttributes are the specific attributes that the Source uses as part of its CloudEvents."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[IntegrationSourceStatusCeAttributesItem.Builder]()
                context._parent_builder = self
                context._field_name = "ce_attributes"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntegrationSourceStatusCeAttributesItem.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("ce_attributes", value)

        @overload
        def conditions(
            self,
            value_or_callback: list[IntegrationSourceStatusConditionsItem] | None,
            /,
        ) -> "IntegrationSourceStatus.Builder": ...

        @overload
        def conditions(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        IntegrationSourceStatusConditionsItem,
                        IntegrationSourceStatusConditionsItem.Builder,
                    ]
                ],
                GenericListBuilder[
                    IntegrationSourceStatusConditionsItem,
                    IntegrationSourceStatusConditionsItem.Builder,
                ]
                | list[IntegrationSourceStatusConditionsItem],
            ],
            /,
        ) -> "IntegrationSourceStatus.Builder": ...

        @overload
        def conditions(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[IntegrationSourceStatusConditionsItem.Builder]: ...

        def conditions(self, value_or_callback=UNSET, /):
            "Conditions the latest available observations of a resource\u0027s current state."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[IntegrationSourceStatusConditionsItem.Builder]()
                context._parent_builder = self
                context._field_name = "conditions"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntegrationSourceStatusConditionsItem.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("conditions", value)

        def observed_generation(self, value: int | None, /) -> Self:
            "ObservedGeneration is the \u0027Generation\u0027 of the Service that was last processed by the controller."
            return self._set("observed_generation", value)

        def sink_uri(self, value: str | None, /) -> Self:
            "SinkURI is the current active sink URI that has been configured for the Source."
            return self._set("sink_uri", value)

        def sink_ca_certs(self, value: str | None, /) -> Self:
            "CACerts is the Certification Authority (CA) certificates in PEM format that the source trusts when sending events to the sink."
            return self._set("sink_ca_certs", value)

        def sink_audience(self, value: str | None, /) -> Self:
            "Audience is the OIDC audience of the sink."
            return self._set("sink_audience", value)

    class BuilderContext(BuilderContextBase["IntegrationSourceStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSourceStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSourceStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["IntegrationSourceStatus", Builder]:
        return GenericListBuilder[IntegrationSourceStatus, IntegrationSourceStatus.Builder]()

    annotations: dict[str, Any] | None = None
    "Annotations is additional Status fields for the Resource to save some additional State as well as convey more information to the user. This is roughly akin to Annotations on any k8s resource, just the reconciler conveying richer information outwards."
    auth: IntegrationSourceStatusAuth | None = None
    "Auth provides the relevant information for OIDC authentication."
    ce_attributes: Annotated[
        list[IntegrationSourceStatusCeAttributesItem] | None,
        Field(alias="ceAttributes"),
    ] = None
    "CloudEventAttributes are the specific attributes that the Source uses as part of its CloudEvents."
    conditions: list[IntegrationSourceStatusConditionsItem] | None = None
    "Conditions the latest available observations of a resource\u0027s current state."
    observed_generation: Annotated[int | None, Field(alias="observedGeneration")] = None
    "ObservedGeneration is the \u0027Generation\u0027 of the Service that was last processed by the controller."
    sink_uri: Annotated[str | None, Field(alias="sinkUri")] = None
    "SinkURI is the current active sink URI that has been configured for the Source."
    sink_ca_certs: Annotated[str | None, Field(alias="sinkCACerts")] = None
    "CACerts is the Certification Authority (CA) certificates in PEM format that the source trusts when sending events to the sink."
    sink_audience: Annotated[str | None, Field(alias="sinkAudience")] = None
    "Audience is the OIDC audience of the sink."


class IntegrationSourceSpecSink(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSourceSpecSink"]:
            return IntegrationSourceSpecSink

        def build(self) -> "IntegrationSourceSpecSink":
            return IntegrationSourceSpecSink(**self._attrs)

        @overload
        def ref(
            self, value_or_callback: IntegrationSourceSpecSinkRef | None, /
        ) -> "IntegrationSourceSpecSink.Builder": ...

        @overload
        def ref(
            self,
            value_or_callback: Callable[
                [IntegrationSourceSpecSinkRef.Builder],
                IntegrationSourceSpecSinkRef.Builder | IntegrationSourceSpecSinkRef,
            ],
            /,
        ) -> "IntegrationSourceSpecSink.Builder": ...

        @overload
        def ref(
            self, value_or_callback: Never = ...
        ) -> "IntegrationSourceSpecSinkRef.BuilderContext": ...

        def ref(self, value_or_callback=UNSET, /):
            "Ref points to an Addressable."
            if self._in_context and value_or_callback is UNSET:
                context = IntegrationSourceSpecSinkRef.BuilderContext()
                context._parent_builder = self
                context._field_name = "ref"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntegrationSourceSpecSinkRef.builder())
                if isinstance(output, IntegrationSourceSpecSinkRef.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("ref", value)

        def uri(self, value: str | None, /) -> Self:
            "URI can be an absolute URL(non-empty scheme and non-empty host) pointing to the target or a relative URI. Relative URIs will be resolved using the base URI retrieved from Ref."
            return self._set("uri", value)

        def ca_certs(self, value: str | None, /) -> Self:
            "CACerts is the Certification Authority (CA) certificates in PEM format that the source trusts when sending events to the sink."
            return self._set("ca_certs", value)

        def audience(self, value: str | None, /) -> Self:
            "Audience is the OIDC audience. This only needs to be set if the target is not an Addressable and thus the Audience can\u0027t be received from the target itself. If specified, it takes precedence over the target\u0027s Audience."
            return self._set("audience", value)

    class BuilderContext(BuilderContextBase["IntegrationSourceSpecSink.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSourceSpecSink.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSourceSpecSink."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["IntegrationSourceSpecSink", Builder]:
        return GenericListBuilder[IntegrationSourceSpecSink, IntegrationSourceSpecSink.Builder]()

    ref: IntegrationSourceSpecSinkRef | None = None
    "Ref points to an Addressable."
    uri: str | None = None
    "URI can be an absolute URL(non-empty scheme and non-empty host) pointing to the target or a relative URI. Relative URIs will be resolved using the base URI retrieved from Ref."
    ca_certs: Annotated[str | None, Field(alias="CACerts")] = None
    "CACerts is the Certification Authority (CA) certificates in PEM format that the source trusts when sending events to the sink."
    audience: str | None = None
    "Audience is the OIDC audience. This only needs to be set if the target is not an Addressable and thus the Audience can\u0027t be received from the target itself. If specified, it takes precedence over the target\u0027s Audience."


class IntegrationSourceSpecAwsAuthSecret(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSourceSpecAwsAuthSecret"]:
            return IntegrationSourceSpecAwsAuthSecret

        def build(self) -> "IntegrationSourceSpecAwsAuthSecret":
            return IntegrationSourceSpecAwsAuthSecret(**self._attrs)

        @overload
        def ref(
            self, value_or_callback: IntegrationSourceSpecAwsAuthSecretRef | None, /
        ) -> "IntegrationSourceSpecAwsAuthSecret.Builder": ...

        @overload
        def ref(
            self,
            value_or_callback: Callable[
                [IntegrationSourceSpecAwsAuthSecretRef.Builder],
                IntegrationSourceSpecAwsAuthSecretRef.Builder
                | IntegrationSourceSpecAwsAuthSecretRef,
            ],
            /,
        ) -> "IntegrationSourceSpecAwsAuthSecret.Builder": ...

        @overload
        def ref(
            self, value_or_callback: Never = ...
        ) -> "IntegrationSourceSpecAwsAuthSecretRef.BuilderContext": ...

        def ref(self, value_or_callback=UNSET, /):
            "Secret reference.\n"
            if self._in_context and value_or_callback is UNSET:
                context = IntegrationSourceSpecAwsAuthSecretRef.BuilderContext()
                context._parent_builder = self
                context._field_name = "ref"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntegrationSourceSpecAwsAuthSecretRef.builder())
                if isinstance(output, IntegrationSourceSpecAwsAuthSecretRef.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("ref", value)

    class BuilderContext(BuilderContextBase["IntegrationSourceSpecAwsAuthSecret.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSourceSpecAwsAuthSecret.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSourceSpecAwsAuthSecret."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["IntegrationSourceSpecAwsAuthSecret", Builder]:
        return GenericListBuilder[
            IntegrationSourceSpecAwsAuthSecret,
            IntegrationSourceSpecAwsAuthSecret.Builder,
        ]()

    ref: IntegrationSourceSpecAwsAuthSecretRef | None = None
    "Secret reference.\n"


class IntegrationSourceSpecAwsAuth(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSourceSpecAwsAuth"]:
            return IntegrationSourceSpecAwsAuth

        def build(self) -> "IntegrationSourceSpecAwsAuth":
            return IntegrationSourceSpecAwsAuth(**self._attrs)

        @overload
        def secret(
            self, value_or_callback: IntegrationSourceSpecAwsAuthSecret | None, /
        ) -> "IntegrationSourceSpecAwsAuth.Builder": ...

        @overload
        def secret(
            self,
            value_or_callback: Callable[
                [IntegrationSourceSpecAwsAuthSecret.Builder],
                IntegrationSourceSpecAwsAuthSecret.Builder | IntegrationSourceSpecAwsAuthSecret,
            ],
            /,
        ) -> "IntegrationSourceSpecAwsAuth.Builder": ...

        @overload
        def secret(
            self, value_or_callback: Never = ...
        ) -> "IntegrationSourceSpecAwsAuthSecret.BuilderContext": ...

        def secret(self, value_or_callback=UNSET, /):
            "Auth secret"
            if self._in_context and value_or_callback is UNSET:
                context = IntegrationSourceSpecAwsAuthSecret.BuilderContext()
                context._parent_builder = self
                context._field_name = "secret"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntegrationSourceSpecAwsAuthSecret.builder())
                if isinstance(output, IntegrationSourceSpecAwsAuthSecret.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("secret", value)

        def service_account_name(self, value: str | None, /) -> Self:
            "Optional ServiceAccount to assign to pod. This enables the pod default credentials to be used instead of the auth secret."
            return self._set("service_account_name", value)

    class BuilderContext(BuilderContextBase["IntegrationSourceSpecAwsAuth.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSourceSpecAwsAuth.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSourceSpecAwsAuth."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["IntegrationSourceSpecAwsAuth", Builder]:
        return GenericListBuilder[
            IntegrationSourceSpecAwsAuth, IntegrationSourceSpecAwsAuth.Builder
        ]()

    secret: IntegrationSourceSpecAwsAuthSecret | None = None
    "Auth secret"
    service_account_name: Annotated[str | None, Field(alias="serviceAccountName")] = None
    "Optional ServiceAccount to assign to pod. This enables the pod default credentials to be used instead of the auth secret."


class IntegrationSourceSpecAws(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSourceSpecAws"]:
            return IntegrationSourceSpecAws

        def build(self) -> "IntegrationSourceSpecAws":
            return IntegrationSourceSpecAws(**self._attrs)

        @overload
        def s3(
            self, value_or_callback: IntegrationSourceSpecAwsS3 | None, /
        ) -> "IntegrationSourceSpecAws.Builder": ...

        @overload
        def s3(
            self,
            value_or_callback: Callable[
                [IntegrationSourceSpecAwsS3.Builder],
                IntegrationSourceSpecAwsS3.Builder | IntegrationSourceSpecAwsS3,
            ],
            /,
        ) -> "IntegrationSourceSpecAws.Builder": ...

        @overload
        def s3(
            self, value_or_callback: Never = ...
        ) -> "IntegrationSourceSpecAwsS3.BuilderContext": ...

        def s3(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = IntegrationSourceSpecAwsS3.BuilderContext()
                context._parent_builder = self
                context._field_name = "s3"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntegrationSourceSpecAwsS3.builder())
                if isinstance(output, IntegrationSourceSpecAwsS3.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("s3", value)

        @overload
        def sqs(
            self, value_or_callback: IntegrationSourceSpecAwsSqs | None, /
        ) -> "IntegrationSourceSpecAws.Builder": ...

        @overload
        def sqs(
            self,
            value_or_callback: Callable[
                [IntegrationSourceSpecAwsSqs.Builder],
                IntegrationSourceSpecAwsSqs.Builder | IntegrationSourceSpecAwsSqs,
            ],
            /,
        ) -> "IntegrationSourceSpecAws.Builder": ...

        @overload
        def sqs(
            self, value_or_callback: Never = ...
        ) -> "IntegrationSourceSpecAwsSqs.BuilderContext": ...

        def sqs(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = IntegrationSourceSpecAwsSqs.BuilderContext()
                context._parent_builder = self
                context._field_name = "sqs"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntegrationSourceSpecAwsSqs.builder())
                if isinstance(output, IntegrationSourceSpecAwsSqs.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("sqs", value)

        @overload
        def ddb_streams(
            self, value_or_callback: IntegrationSourceSpecAwsDdbStreams | None, /
        ) -> "IntegrationSourceSpecAws.Builder": ...

        @overload
        def ddb_streams(
            self,
            value_or_callback: Callable[
                [IntegrationSourceSpecAwsDdbStreams.Builder],
                IntegrationSourceSpecAwsDdbStreams.Builder | IntegrationSourceSpecAwsDdbStreams,
            ],
            /,
        ) -> "IntegrationSourceSpecAws.Builder": ...

        @overload
        def ddb_streams(
            self, value_or_callback: Never = ...
        ) -> "IntegrationSourceSpecAwsDdbStreams.BuilderContext": ...

        def ddb_streams(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = IntegrationSourceSpecAwsDdbStreams.BuilderContext()
                context._parent_builder = self
                context._field_name = "ddb_streams"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntegrationSourceSpecAwsDdbStreams.builder())
                if isinstance(output, IntegrationSourceSpecAwsDdbStreams.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("ddb_streams", value)

        @overload
        def auth(
            self, value_or_callback: IntegrationSourceSpecAwsAuth | None, /
        ) -> "IntegrationSourceSpecAws.Builder": ...

        @overload
        def auth(
            self,
            value_or_callback: Callable[
                [IntegrationSourceSpecAwsAuth.Builder],
                IntegrationSourceSpecAwsAuth.Builder | IntegrationSourceSpecAwsAuth,
            ],
            /,
        ) -> "IntegrationSourceSpecAws.Builder": ...

        @overload
        def auth(
            self, value_or_callback: Never = ...
        ) -> "IntegrationSourceSpecAwsAuth.BuilderContext": ...

        def auth(self, value_or_callback=UNSET, /):
            "Auth configurations"
            if self._in_context and value_or_callback is UNSET:
                context = IntegrationSourceSpecAwsAuth.BuilderContext()
                context._parent_builder = self
                context._field_name = "auth"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntegrationSourceSpecAwsAuth.builder())
                if isinstance(output, IntegrationSourceSpecAwsAuth.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("auth", value)

    class BuilderContext(BuilderContextBase["IntegrationSourceSpecAws.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSourceSpecAws.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSourceSpecAws."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["IntegrationSourceSpecAws", Builder]:
        return GenericListBuilder[IntegrationSourceSpecAws, IntegrationSourceSpecAws.Builder]()

    s3: IntegrationSourceSpecAwsS3 | None = None
    sqs: IntegrationSourceSpecAwsSqs | None = None
    ddb_streams: Annotated[IntegrationSourceSpecAwsDdbStreams | None, Field(alias="ddbStreams")] = (
        None
    )
    auth: IntegrationSourceSpecAwsAuth | None = None
    "Auth configurations"


class IntegrationSourceSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSourceSpec"]:
            return IntegrationSourceSpec

        def build(self) -> "IntegrationSourceSpec":
            return IntegrationSourceSpec(**self._attrs)

        @overload
        def ce_overrides(
            self, value_or_callback: IntegrationSourceSpecCeOverrides | None, /
        ) -> "IntegrationSourceSpec.Builder": ...

        @overload
        def ce_overrides(
            self,
            value_or_callback: Callable[
                [IntegrationSourceSpecCeOverrides.Builder],
                IntegrationSourceSpecCeOverrides.Builder | IntegrationSourceSpecCeOverrides,
            ],
            /,
        ) -> "IntegrationSourceSpec.Builder": ...

        @overload
        def ce_overrides(
            self, value_or_callback: Never = ...
        ) -> "IntegrationSourceSpecCeOverrides.BuilderContext": ...

        def ce_overrides(self, value_or_callback=UNSET, /):
            "CloudEventOverrides defines overrides to control the output format and modifications of the event sent to the sink."
            if self._in_context and value_or_callback is UNSET:
                context = IntegrationSourceSpecCeOverrides.BuilderContext()
                context._parent_builder = self
                context._field_name = "ce_overrides"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntegrationSourceSpecCeOverrides.builder())
                if isinstance(output, IntegrationSourceSpecCeOverrides.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("ce_overrides", value)

        @overload
        def sink(
            self, value_or_callback: IntegrationSourceSpecSink | None, /
        ) -> "IntegrationSourceSpec.Builder": ...

        @overload
        def sink(
            self,
            value_or_callback: Callable[
                [IntegrationSourceSpecSink.Builder],
                IntegrationSourceSpecSink.Builder | IntegrationSourceSpecSink,
            ],
            /,
        ) -> "IntegrationSourceSpec.Builder": ...

        @overload
        def sink(
            self, value_or_callback: Never = ...
        ) -> "IntegrationSourceSpecSink.BuilderContext": ...

        def sink(self, value_or_callback=UNSET, /):
            "Sink is a reference to an object that will resolve to a uri to use as the sink."
            if self._in_context and value_or_callback is UNSET:
                context = IntegrationSourceSpecSink.BuilderContext()
                context._parent_builder = self
                context._field_name = "sink"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntegrationSourceSpecSink.builder())
                if isinstance(output, IntegrationSourceSpecSink.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("sink", value)

        @overload
        def timer(
            self, value_or_callback: IntegrationSourceSpecTimer | None, /
        ) -> "IntegrationSourceSpec.Builder": ...

        @overload
        def timer(
            self,
            value_or_callback: Callable[
                [IntegrationSourceSpecTimer.Builder],
                IntegrationSourceSpecTimer.Builder | IntegrationSourceSpecTimer,
            ],
            /,
        ) -> "IntegrationSourceSpec.Builder": ...

        @overload
        def timer(
            self, value_or_callback: Never = ...
        ) -> "IntegrationSourceSpecTimer.BuilderContext": ...

        def timer(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = IntegrationSourceSpecTimer.BuilderContext()
                context._parent_builder = self
                context._field_name = "timer"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntegrationSourceSpecTimer.builder())
                if isinstance(output, IntegrationSourceSpecTimer.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("timer", value)

        @overload
        def aws(
            self, value_or_callback: IntegrationSourceSpecAws | None, /
        ) -> "IntegrationSourceSpec.Builder": ...

        @overload
        def aws(
            self,
            value_or_callback: Callable[
                [IntegrationSourceSpecAws.Builder],
                IntegrationSourceSpecAws.Builder | IntegrationSourceSpecAws,
            ],
            /,
        ) -> "IntegrationSourceSpec.Builder": ...

        @overload
        def aws(
            self, value_or_callback: Never = ...
        ) -> "IntegrationSourceSpecAws.BuilderContext": ...

        def aws(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = IntegrationSourceSpecAws.BuilderContext()
                context._parent_builder = self
                context._field_name = "aws"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntegrationSourceSpecAws.builder())
                if isinstance(output, IntegrationSourceSpecAws.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("aws", value)

        def template(self, value: dict[str, Any] | None, /) -> Self:
            "A template in the shape of `Deployment.spec.template` to be used for this ContainerSource. More info: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/"
            return self._set("template", value)

    class BuilderContext(BuilderContextBase["IntegrationSourceSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSourceSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSourceSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["IntegrationSourceSpec", Builder]:
        return GenericListBuilder[IntegrationSourceSpec, IntegrationSourceSpec.Builder]()

    ce_overrides: Annotated[IntegrationSourceSpecCeOverrides | None, Field(alias="ceOverrides")] = (
        None
    )
    "CloudEventOverrides defines overrides to control the output format and modifications of the event sent to the sink."
    sink: IntegrationSourceSpecSink | None = None
    "Sink is a reference to an object that will resolve to a uri to use as the sink."
    timer: IntegrationSourceSpecTimer | None = None
    aws: IntegrationSourceSpecAws | None = None
    template: dict[str, Any] | None = None
    "A template in the shape of `Deployment.spec.template` to be used for this ContainerSource. More info: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/"


class IntegrationSource(Resource):
    __cloudcoil_api__: ClassVar[dict] = {
        "plural": "integrationsources",
        "scope": "Namespaced",
        "status": True,
    }

    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSource"]:
            return IntegrationSource

        def build(self) -> "IntegrationSource":
            return IntegrationSource(**self._attrs)

        @overload
        def spec(
            self, value_or_callback: IntegrationSourceSpec | None, /
        ) -> "IntegrationSource.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[
                [IntegrationSourceSpec.Builder],
                IntegrationSourceSpec.Builder | IntegrationSourceSpec,
            ],
            /,
        ) -> "IntegrationSource.Builder": ...

        @overload
        def spec(
            self, value_or_callback: Never = ...
        ) -> "IntegrationSourceSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = IntegrationSourceSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntegrationSourceSpec.builder())
                if isinstance(output, IntegrationSourceSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

        @overload
        def status(
            self, value_or_callback: IntegrationSourceStatus | None, /
        ) -> "IntegrationSource.Builder": ...

        @overload
        def status(
            self,
            value_or_callback: Callable[
                [IntegrationSourceStatus.Builder],
                IntegrationSourceStatus.Builder | IntegrationSourceStatus,
            ],
            /,
        ) -> "IntegrationSource.Builder": ...

        @overload
        def status(
            self, value_or_callback: Never = ...
        ) -> "IntegrationSourceStatus.BuilderContext": ...

        def status(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = IntegrationSourceStatus.BuilderContext()
                context._parent_builder = self
                context._field_name = "status"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntegrationSourceStatus.builder())
                if isinstance(output, IntegrationSourceStatus.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("status", value)

        def api_version(self, value: Literal["sources.knative.dev/v1alpha1"], /) -> Self:
            return self._set("api_version", value)

        def kind(self, value: Literal["IntegrationSource"], /) -> Self:
            return self._set("kind", value)

        @overload
        def metadata(
            self, value_or_callback: ObjectMeta | None, /
        ) -> "IntegrationSource.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "IntegrationSource.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

    class BuilderContext(BuilderContextBase["IntegrationSource.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSource.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSource."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["IntegrationSource", Builder]:
        return GenericListBuilder[IntegrationSource, IntegrationSource.Builder]()

    spec: IntegrationSourceSpec | None = None
    status: IntegrationSourceStatus | None = None
    api_version: Annotated[Literal["sources.knative.dev/v1alpha1"], Field(alias="apiVersion")] = (
        "sources.knative.dev/v1alpha1"
    )
    kind: Literal["IntegrationSource"] = "IntegrationSource"
    metadata: ObjectMeta | None = None
