# Generated by cloudcoil-model-codegen v0.7.1
# DO NOT EDIT

from typing import (
    Annotated,
    Any,
    Callable,
    ClassVar,
    Literal,
    overload,
)

from cloudcoil.apimachinery import ObjectMeta
from cloudcoil.pydantic import (
    UNSET,
    BaseModel,
    BaseModelBuilder,
    BuilderContextBase,
    GenericListBuilder,
    ListBuilderContext,
    Never,
    Self,
)
from cloudcoil.resources import Resource
from pydantic import Field


class PingSourceSpecCeOverrides(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["PingSourceSpecCeOverrides"]:
            return PingSourceSpecCeOverrides

        def build(self) -> "PingSourceSpecCeOverrides":
            return PingSourceSpecCeOverrides(**self._attrs)

        def extensions(self, value: dict[str, str] | None, /) -> Self:
            "Extensions specify what attribute are added or overridden on the outbound event. Each `Extensions` key-value pair are set on the event as an attribute extension independently."
            return self._set("extensions", value)

    class BuilderContext(BuilderContextBase["PingSourceSpecCeOverrides.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = PingSourceSpecCeOverrides.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for PingSourceSpecCeOverrides."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["PingSourceSpecCeOverrides", Builder]:
        return GenericListBuilder[PingSourceSpecCeOverrides, PingSourceSpecCeOverrides.Builder]()

    extensions: dict[str, str] | None = None
    "Extensions specify what attribute are added or overridden on the outbound event. Each `Extensions` key-value pair are set on the event as an attribute extension independently."


class PingSourceSpecSinkRef(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["PingSourceSpecSinkRef"]:
            return PingSourceSpecSinkRef

        def build(self) -> "PingSourceSpecSinkRef":
            return PingSourceSpecSinkRef(**self._attrs)

        def api_version(self, value: str | None, /) -> Self:
            "API version of the referent."
            return self._set("api_version", value)

        def kind(self, value: str | None, /) -> Self:
            "Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        def name(self, value: str | None, /) -> Self:
            "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
            return self._set("name", value)

        def namespace(self, value: str | None, /) -> Self:
            "Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/ This is optional field, it gets defaulted to the object holding it if left out."
            return self._set("namespace", value)

    class BuilderContext(BuilderContextBase["PingSourceSpecSinkRef.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = PingSourceSpecSinkRef.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for PingSourceSpecSinkRef."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["PingSourceSpecSinkRef", Builder]:
        return GenericListBuilder[PingSourceSpecSinkRef, PingSourceSpecSinkRef.Builder]()

    api_version: Annotated[str | None, Field(alias="apiVersion")] = None
    "API version of the referent."
    kind: str | None = None
    "Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    name: str | None = None
    "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
    namespace: str | None = None
    "Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/ This is optional field, it gets defaulted to the object holding it if left out."


class PingSourceStatusAuth(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["PingSourceStatusAuth"]:
            return PingSourceStatusAuth

        def build(self) -> "PingSourceStatusAuth":
            return PingSourceStatusAuth(**self._attrs)

        def service_account_name(self, value: str | None, /) -> Self:
            "ServiceAccountName is the name of the generated service account used for this components OIDC authentication."
            return self._set("service_account_name", value)

        def service_account_names(self, value: list[str] | None, /) -> Self:
            "ServiceAccountNames is the list of names of the generated service accounts used for this components OIDC authentication."
            return self._set("service_account_names", value)

    class BuilderContext(BuilderContextBase["PingSourceStatusAuth.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = PingSourceStatusAuth.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for PingSourceStatusAuth."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["PingSourceStatusAuth", Builder]:
        return GenericListBuilder[PingSourceStatusAuth, PingSourceStatusAuth.Builder]()

    service_account_name: Annotated[str | None, Field(alias="serviceAccountName")] = None
    "ServiceAccountName is the name of the generated service account used for this components OIDC authentication."
    service_account_names: Annotated[list[str] | None, Field(alias="serviceAccountNames")] = None
    "ServiceAccountNames is the list of names of the generated service accounts used for this components OIDC authentication."


class PingSourceStatusCeAttributesItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["PingSourceStatusCeAttributesItem"]:
            return PingSourceStatusCeAttributesItem

        def build(self) -> "PingSourceStatusCeAttributesItem":
            return PingSourceStatusCeAttributesItem(**self._attrs)

        def source(self, value: str | None, /) -> Self:
            "Source is the CloudEvents source attribute."
            return self._set("source", value)

        def type(self, value: str | None, /) -> Self:
            "Type refers to the CloudEvent type attribute."
            return self._set("type", value)

    class BuilderContext(BuilderContextBase["PingSourceStatusCeAttributesItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = PingSourceStatusCeAttributesItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for PingSourceStatusCeAttributesItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["PingSourceStatusCeAttributesItem", Builder]:
        return GenericListBuilder[
            PingSourceStatusCeAttributesItem, PingSourceStatusCeAttributesItem.Builder
        ]()

    source: str | None = None
    "Source is the CloudEvents source attribute."
    type: str | None = None
    "Type refers to the CloudEvent type attribute."


class PingSourceStatusConditionsItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["PingSourceStatusConditionsItem"]:
            return PingSourceStatusConditionsItem

        def build(self) -> "PingSourceStatusConditionsItem":
            return PingSourceStatusConditionsItem(**self._attrs)

        def last_transition_time(self, value: str | None, /) -> Self:
            "LastTransitionTime is the last time the condition transitioned from one status to another. We use VolatileTime in place of metav1.Time to exclude this from creating equality.Semantic differences (all other things held constant)."
            return self._set("last_transition_time", value)

        def message(self, value: str | None, /) -> Self:
            "A human readable message indicating details about the transition."
            return self._set("message", value)

        def reason(self, value: str | None, /) -> Self:
            "The reason for the condition\u0027s last transition."
            return self._set("reason", value)

        def severity(self, value: str | None, /) -> Self:
            "Severity with which to treat failures of this type of condition. When this is not specified, it defaults to Error."
            return self._set("severity", value)

        def status(self, value: str, /) -> Self:
            "Status of the condition, one of True, False, Unknown."
            return self._set("status", value)

        def type(self, value: str, /) -> Self:
            "Type of condition."
            return self._set("type", value)

    class BuilderContext(BuilderContextBase["PingSourceStatusConditionsItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = PingSourceStatusConditionsItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for PingSourceStatusConditionsItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["PingSourceStatusConditionsItem", Builder]:
        return GenericListBuilder[
            PingSourceStatusConditionsItem, PingSourceStatusConditionsItem.Builder
        ]()

    last_transition_time: Annotated[str | None, Field(alias="lastTransitionTime")] = None
    "LastTransitionTime is the last time the condition transitioned from one status to another. We use VolatileTime in place of metav1.Time to exclude this from creating equality.Semantic differences (all other things held constant)."
    message: str | None = None
    "A human readable message indicating details about the transition."
    reason: str | None = None
    "The reason for the condition\u0027s last transition."
    severity: str | None = None
    "Severity with which to treat failures of this type of condition. When this is not specified, it defaults to Error."
    status: str
    "Status of the condition, one of True, False, Unknown."
    type: str
    "Type of condition."


class PingSourceStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["PingSourceStatus"]:
            return PingSourceStatus

        def build(self) -> "PingSourceStatus":
            return PingSourceStatus(**self._attrs)

        def annotations(self, value: dict[str, Any] | None, /) -> Self:
            "Annotations is additional Status fields for the Resource to save some additional State as well as convey more information to the user. This is roughly akin to Annotations on any k8s resource, just the reconciler conveying richer information outwards."
            return self._set("annotations", value)

        @overload
        def auth(
            self, value_or_callback: PingSourceStatusAuth | None, /
        ) -> "PingSourceStatus.Builder": ...

        @overload
        def auth(
            self,
            value_or_callback: Callable[
                [PingSourceStatusAuth.Builder],
                PingSourceStatusAuth.Builder | PingSourceStatusAuth,
            ],
            /,
        ) -> "PingSourceStatus.Builder": ...

        @overload
        def auth(self, value_or_callback: Never = ...) -> "PingSourceStatusAuth.BuilderContext": ...

        def auth(self, value_or_callback=UNSET, /):
            "Auth provides the relevant information for OIDC authentication."
            if self._in_context and value_or_callback is UNSET:
                context = PingSourceStatusAuth.BuilderContext()
                context._parent_builder = self
                context._field_name = "auth"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(PingSourceStatusAuth.builder())
                if isinstance(output, PingSourceStatusAuth.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("auth", value)

        @overload
        def ce_attributes(
            self, value_or_callback: list[PingSourceStatusCeAttributesItem] | None, /
        ) -> "PingSourceStatus.Builder": ...

        @overload
        def ce_attributes(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        PingSourceStatusCeAttributesItem,
                        PingSourceStatusCeAttributesItem.Builder,
                    ]
                ],
                GenericListBuilder[
                    PingSourceStatusCeAttributesItem,
                    PingSourceStatusCeAttributesItem.Builder,
                ]
                | list[PingSourceStatusCeAttributesItem],
            ],
            /,
        ) -> "PingSourceStatus.Builder": ...

        @overload
        def ce_attributes(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[PingSourceStatusCeAttributesItem.Builder]: ...

        def ce_attributes(self, value_or_callback=UNSET, /):
            "CloudEventAttributes are the specific attributes that the Source uses as part of its CloudEvents."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[PingSourceStatusCeAttributesItem.Builder]()
                context._parent_builder = self
                context._field_name = "ce_attributes"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(PingSourceStatusCeAttributesItem.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("ce_attributes", value)

        @overload
        def conditions(
            self, value_or_callback: list[PingSourceStatusConditionsItem] | None, /
        ) -> "PingSourceStatus.Builder": ...

        @overload
        def conditions(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        PingSourceStatusConditionsItem,
                        PingSourceStatusConditionsItem.Builder,
                    ]
                ],
                GenericListBuilder[
                    PingSourceStatusConditionsItem,
                    PingSourceStatusConditionsItem.Builder,
                ]
                | list[PingSourceStatusConditionsItem],
            ],
            /,
        ) -> "PingSourceStatus.Builder": ...

        @overload
        def conditions(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[PingSourceStatusConditionsItem.Builder]: ...

        def conditions(self, value_or_callback=UNSET, /):
            "Conditions the latest available observations of a resource\u0027s current state."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[PingSourceStatusConditionsItem.Builder]()
                context._parent_builder = self
                context._field_name = "conditions"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(PingSourceStatusConditionsItem.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("conditions", value)

        def observed_generation(self, value: int | None, /) -> Self:
            'ObservedGeneration is the "Generation" of the Service that was last processed by the controller.'
            return self._set("observed_generation", value)

        def sink_uri(self, value: str | None, /) -> Self:
            "SinkURI is the current active sink URI that has been configured for the Source."
            return self._set("sink_uri", value)

        def sink_ca_certs(self, value: str | None, /) -> Self:
            "CACerts is the Certification Authority (CA) certificates in PEM format that the source trusts when sending events to the sink."
            return self._set("sink_ca_certs", value)

        def sink_audience(self, value: str | None, /) -> Self:
            "sinkAudience is the OIDC audience of the sink."
            return self._set("sink_audience", value)

    class BuilderContext(BuilderContextBase["PingSourceStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = PingSourceStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for PingSourceStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["PingSourceStatus", Builder]:
        return GenericListBuilder[PingSourceStatus, PingSourceStatus.Builder]()

    annotations: dict[str, Any] | None = None
    "Annotations is additional Status fields for the Resource to save some additional State as well as convey more information to the user. This is roughly akin to Annotations on any k8s resource, just the reconciler conveying richer information outwards."
    auth: PingSourceStatusAuth | None = None
    "Auth provides the relevant information for OIDC authentication."
    ce_attributes: Annotated[
        list[PingSourceStatusCeAttributesItem] | None, Field(alias="ceAttributes")
    ] = None
    "CloudEventAttributes are the specific attributes that the Source uses as part of its CloudEvents."
    conditions: list[PingSourceStatusConditionsItem] | None = None
    "Conditions the latest available observations of a resource\u0027s current state."
    observed_generation: Annotated[int | None, Field(alias="observedGeneration")] = None
    'ObservedGeneration is the "Generation" of the Service that was last processed by the controller.'
    sink_uri: Annotated[str | None, Field(alias="sinkUri")] = None
    "SinkURI is the current active sink URI that has been configured for the Source."
    sink_ca_certs: Annotated[str | None, Field(alias="sinkCACerts")] = None
    "CACerts is the Certification Authority (CA) certificates in PEM format that the source trusts when sending events to the sink."
    sink_audience: Annotated[str | None, Field(alias="sinkAudience")] = None
    "sinkAudience is the OIDC audience of the sink."


class PingSourceSpecSink(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["PingSourceSpecSink"]:
            return PingSourceSpecSink

        def build(self) -> "PingSourceSpecSink":
            return PingSourceSpecSink(**self._attrs)

        @overload
        def ref(
            self, value_or_callback: PingSourceSpecSinkRef | None, /
        ) -> "PingSourceSpecSink.Builder": ...

        @overload
        def ref(
            self,
            value_or_callback: Callable[
                [PingSourceSpecSinkRef.Builder],
                PingSourceSpecSinkRef.Builder | PingSourceSpecSinkRef,
            ],
            /,
        ) -> "PingSourceSpecSink.Builder": ...

        @overload
        def ref(self, value_or_callback: Never = ...) -> "PingSourceSpecSinkRef.BuilderContext": ...

        def ref(self, value_or_callback=UNSET, /):
            "Ref points to an Addressable."
            if self._in_context and value_or_callback is UNSET:
                context = PingSourceSpecSinkRef.BuilderContext()
                context._parent_builder = self
                context._field_name = "ref"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(PingSourceSpecSinkRef.builder())
                if isinstance(output, PingSourceSpecSinkRef.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("ref", value)

        def uri(self, value: str | None, /) -> Self:
            "URI can be an absolute URL(non-empty scheme and non-empty host) pointing to the target or a relative URI. Relative URIs will be resolved using the base URI retrieved from Ref."
            return self._set("uri", value)

        def ca_certs(self, value: str | None, /) -> Self:
            "CACerts is the Certification Authority (CA) certificates in PEM format that the source trusts when sending events to the sink."
            return self._set("ca_certs", value)

        def audience(self, value: str | None, /) -> Self:
            "Audience is the OIDC audience. This only needs to be set if the target is not an Addressable and thus the Audience can\u0027t be received from the target itself. If specified, it takes precedence over the target\u0027s Audience."
            return self._set("audience", value)

    class BuilderContext(BuilderContextBase["PingSourceSpecSink.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = PingSourceSpecSink.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for PingSourceSpecSink."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["PingSourceSpecSink", Builder]:
        return GenericListBuilder[PingSourceSpecSink, PingSourceSpecSink.Builder]()

    ref: PingSourceSpecSinkRef | None = None
    "Ref points to an Addressable."
    uri: str | None = None
    "URI can be an absolute URL(non-empty scheme and non-empty host) pointing to the target or a relative URI. Relative URIs will be resolved using the base URI retrieved from Ref."
    ca_certs: Annotated[str | None, Field(alias="CACerts")] = None
    "CACerts is the Certification Authority (CA) certificates in PEM format that the source trusts when sending events to the sink."
    audience: str | None = None
    "Audience is the OIDC audience. This only needs to be set if the target is not an Addressable and thus the Audience can\u0027t be received from the target itself. If specified, it takes precedence over the target\u0027s Audience."


class PingSourceSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["PingSourceSpec"]:
            return PingSourceSpec

        def build(self) -> "PingSourceSpec":
            return PingSourceSpec(**self._attrs)

        @overload
        def ce_overrides(
            self, value_or_callback: PingSourceSpecCeOverrides | None, /
        ) -> "PingSourceSpec.Builder": ...

        @overload
        def ce_overrides(
            self,
            value_or_callback: Callable[
                [PingSourceSpecCeOverrides.Builder],
                PingSourceSpecCeOverrides.Builder | PingSourceSpecCeOverrides,
            ],
            /,
        ) -> "PingSourceSpec.Builder": ...

        @overload
        def ce_overrides(
            self, value_or_callback: Never = ...
        ) -> "PingSourceSpecCeOverrides.BuilderContext": ...

        def ce_overrides(self, value_or_callback=UNSET, /):
            "CloudEventOverrides defines overrides to control the output format and modifications of the event sent to the sink."
            if self._in_context and value_or_callback is UNSET:
                context = PingSourceSpecCeOverrides.BuilderContext()
                context._parent_builder = self
                context._field_name = "ce_overrides"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(PingSourceSpecCeOverrides.builder())
                if isinstance(output, PingSourceSpecCeOverrides.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("ce_overrides", value)

        def content_type(self, value: str | None, /) -> Self:
            "ContentType is the media type of `data` or `dataBase64`. Default is empty."
            return self._set("content_type", value)

        def data(self, value: str | None, /) -> Self:
            "Data is data used as the body of the event posted to the sink. Default is empty. Mutually exclusive with `dataBase64`."
            return self._set("data", value)

        def data_base64(self, value: str | None, /) -> Self:
            "DataBase64 is the base64-encoded string of the actual event\u0027s body posted to the sink. Default is empty. Mutually exclusive with `data`."
            return self._set("data_base64", value)

        def schedule(self, value: str | None, /) -> Self:
            "Schedule is the cron schedule. Defaults to `* * * * *`."
            return self._set("schedule", value)

        @overload
        def sink(
            self, value_or_callback: PingSourceSpecSink | None, /
        ) -> "PingSourceSpec.Builder": ...

        @overload
        def sink(
            self,
            value_or_callback: Callable[
                [PingSourceSpecSink.Builder],
                PingSourceSpecSink.Builder | PingSourceSpecSink,
            ],
            /,
        ) -> "PingSourceSpec.Builder": ...

        @overload
        def sink(self, value_or_callback: Never = ...) -> "PingSourceSpecSink.BuilderContext": ...

        def sink(self, value_or_callback=UNSET, /):
            "Sink is a reference to an object that will resolve to a uri to use as the sink."
            if self._in_context and value_or_callback is UNSET:
                context = PingSourceSpecSink.BuilderContext()
                context._parent_builder = self
                context._field_name = "sink"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(PingSourceSpecSink.builder())
                if isinstance(output, PingSourceSpecSink.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("sink", value)

        def timezone(self, value: str | None, /) -> Self:
            "Timezone modifies the actual time relative to the specified timezone. Defaults to the system time zone. More general information about time zones: https://www.iana.org/time-zones List of valid timezone values: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones"
            return self._set("timezone", value)

    class BuilderContext(BuilderContextBase["PingSourceSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = PingSourceSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for PingSourceSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["PingSourceSpec", Builder]:
        return GenericListBuilder[PingSourceSpec, PingSourceSpec.Builder]()

    ce_overrides: Annotated[PingSourceSpecCeOverrides | None, Field(alias="ceOverrides")] = None
    "CloudEventOverrides defines overrides to control the output format and modifications of the event sent to the sink."
    content_type: Annotated[str | None, Field(alias="contentType")] = None
    "ContentType is the media type of `data` or `dataBase64`. Default is empty."
    data: str | None = None
    "Data is data used as the body of the event posted to the sink. Default is empty. Mutually exclusive with `dataBase64`."
    data_base64: Annotated[str | None, Field(alias="dataBase64")] = None
    "DataBase64 is the base64-encoded string of the actual event\u0027s body posted to the sink. Default is empty. Mutually exclusive with `data`."
    schedule: str | None = None
    "Schedule is the cron schedule. Defaults to `* * * * *`."
    sink: PingSourceSpecSink | None = None
    "Sink is a reference to an object that will resolve to a uri to use as the sink."
    timezone: str | None = None
    "Timezone modifies the actual time relative to the specified timezone. Defaults to the system time zone. More general information about time zones: https://www.iana.org/time-zones List of valid timezone values: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones"


class PingSource(Resource):
    __cloudcoil_api__: ClassVar[dict] = {
        "plural": "pingsources",
        "scope": "Namespaced",
        "status": True,
    }

    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["PingSource"]:
            return PingSource

        def build(self) -> "PingSource":
            return PingSource(**self._attrs)

        @overload
        def spec(self, value_or_callback: PingSourceSpec | None, /) -> "PingSource.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[
                [PingSourceSpec.Builder], PingSourceSpec.Builder | PingSourceSpec
            ],
            /,
        ) -> "PingSource.Builder": ...

        @overload
        def spec(self, value_or_callback: Never = ...) -> "PingSourceSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = PingSourceSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(PingSourceSpec.builder())
                if isinstance(output, PingSourceSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

        @overload
        def status(self, value_or_callback: PingSourceStatus | None, /) -> "PingSource.Builder": ...

        @overload
        def status(
            self,
            value_or_callback: Callable[
                [PingSourceStatus.Builder], PingSourceStatus.Builder | PingSourceStatus
            ],
            /,
        ) -> "PingSource.Builder": ...

        @overload
        def status(self, value_or_callback: Never = ...) -> "PingSourceStatus.BuilderContext": ...

        def status(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = PingSourceStatus.BuilderContext()
                context._parent_builder = self
                context._field_name = "status"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(PingSourceStatus.builder())
                if isinstance(output, PingSourceStatus.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("status", value)

        def api_version(self, value: Literal["sources.knative.dev/v1beta2"], /) -> Self:
            return self._set("api_version", value)

        def kind(self, value: Literal["PingSource"], /) -> Self:
            return self._set("kind", value)

        @overload
        def metadata(self, value_or_callback: ObjectMeta | None, /) -> "PingSource.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "PingSource.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

    class BuilderContext(BuilderContextBase["PingSource.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = PingSource.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for PingSource."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["PingSource", Builder]:
        return GenericListBuilder[PingSource, PingSource.Builder]()

    spec: PingSourceSpec | None = None
    status: PingSourceStatus | None = None
    api_version: Annotated[Literal["sources.knative.dev/v1beta2"], Field(alias="apiVersion")] = (
        "sources.knative.dev/v1beta2"
    )
    kind: Literal["PingSource"] = "PingSource"
    metadata: ObjectMeta | None = None
