# Generated by cloudcoil-model-codegen; DO NOT EDIT
from importlib import import_module
from typing import TYPE_CHECKING, Literal, overload

from cloudcoil.resources import Resource

if TYPE_CHECKING:
    from cloudcoil.models.knative_eventing.eventing_knative_dev.v1 import Broker as _Resource1
    from cloudcoil.models.knative_eventing.eventing_knative_dev.v1 import Trigger as _Resource19
    from cloudcoil.models.knative_eventing.eventing_knative_dev.v1alpha1 import (
        EventPolicy as _Resource4,
    )
    from cloudcoil.models.knative_eventing.eventing_knative_dev.v1alpha1 import (
        EventTransform as _Resource5,
    )
    from cloudcoil.models.knative_eventing.eventing_knative_dev.v1alpha1 import (
        RequestReply as _Resource15,
    )
    from cloudcoil.models.knative_eventing.eventing_knative_dev.v1beta1 import (
        EventType as _Resource6,
    )
    from cloudcoil.models.knative_eventing.eventing_knative_dev.v1beta2 import (
        EventType as _Resource7,
    )
    from cloudcoil.models.knative_eventing.eventing_knative_dev.v1beta3 import (
        EventType as _Resource8,
    )
    from cloudcoil.models.knative_eventing.flows_knative_dev.v1 import Parallel as _Resource12
    from cloudcoil.models.knative_eventing.flows_knative_dev.v1 import Sequence as _Resource16
    from cloudcoil.models.knative_eventing.messaging_knative_dev.v1 import Channel as _Resource2
    from cloudcoil.models.knative_eventing.messaging_knative_dev.v1 import (
        Subscription as _Resource18,
    )
    from cloudcoil.models.knative_eventing.sinks_knative_dev.v1alpha1 import (
        IntegrationSink as _Resource9,
    )
    from cloudcoil.models.knative_eventing.sinks_knative_dev.v1alpha1 import JobSink as _Resource11
    from cloudcoil.models.knative_eventing.sources_knative_dev.v1 import (
        ApiServerSource as _Resource0,
    )
    from cloudcoil.models.knative_eventing.sources_knative_dev.v1 import (
        ContainerSource as _Resource3,
    )
    from cloudcoil.models.knative_eventing.sources_knative_dev.v1 import PingSource as _Resource13
    from cloudcoil.models.knative_eventing.sources_knative_dev.v1 import SinkBinding as _Resource17
    from cloudcoil.models.knative_eventing.sources_knative_dev.v1alpha1 import (
        IntegrationSource as _Resource10,
    )
    from cloudcoil.models.knative_eventing.sources_knative_dev.v1beta2 import (
        PingSource as _Resource14,
    )

_MODELS = {
    ("ApiServerSource", "sources.knative.dev/v1"): (
        "cloudcoil.models.knative_eventing.sources_knative_dev.v1",
        "ApiServerSource",
    ),
    ("ApiServerSource", ""): (
        "cloudcoil.models.knative_eventing.sources_knative_dev.v1",
        "ApiServerSource",
    ),
    ("Broker", "eventing.knative.dev/v1"): (
        "cloudcoil.models.knative_eventing.eventing_knative_dev.v1",
        "Broker",
    ),
    ("Broker", ""): ("cloudcoil.models.knative_eventing.eventing_knative_dev.v1", "Broker"),
    ("Channel", "messaging.knative.dev/v1"): (
        "cloudcoil.models.knative_eventing.messaging_knative_dev.v1",
        "Channel",
    ),
    ("Channel", ""): ("cloudcoil.models.knative_eventing.messaging_knative_dev.v1", "Channel"),
    ("ContainerSource", "sources.knative.dev/v1"): (
        "cloudcoil.models.knative_eventing.sources_knative_dev.v1",
        "ContainerSource",
    ),
    ("ContainerSource", ""): (
        "cloudcoil.models.knative_eventing.sources_knative_dev.v1",
        "ContainerSource",
    ),
    ("EventPolicy", "eventing.knative.dev/v1alpha1"): (
        "cloudcoil.models.knative_eventing.eventing_knative_dev.v1alpha1",
        "EventPolicy",
    ),
    ("EventPolicy", ""): (
        "cloudcoil.models.knative_eventing.eventing_knative_dev.v1alpha1",
        "EventPolicy",
    ),
    ("EventTransform", "eventing.knative.dev/v1alpha1"): (
        "cloudcoil.models.knative_eventing.eventing_knative_dev.v1alpha1",
        "EventTransform",
    ),
    ("EventTransform", ""): (
        "cloudcoil.models.knative_eventing.eventing_knative_dev.v1alpha1",
        "EventTransform",
    ),
    ("EventType", "eventing.knative.dev/v1beta1"): (
        "cloudcoil.models.knative_eventing.eventing_knative_dev.v1beta1",
        "EventType",
    ),
    ("EventType", "eventing.knative.dev/v1beta2"): (
        "cloudcoil.models.knative_eventing.eventing_knative_dev.v1beta2",
        "EventType",
    ),
    ("EventType", "eventing.knative.dev/v1beta3"): (
        "cloudcoil.models.knative_eventing.eventing_knative_dev.v1beta3",
        "EventType",
    ),
    ("IntegrationSink", "sinks.knative.dev/v1alpha1"): (
        "cloudcoil.models.knative_eventing.sinks_knative_dev.v1alpha1",
        "IntegrationSink",
    ),
    ("IntegrationSink", ""): (
        "cloudcoil.models.knative_eventing.sinks_knative_dev.v1alpha1",
        "IntegrationSink",
    ),
    ("IntegrationSource", "sources.knative.dev/v1alpha1"): (
        "cloudcoil.models.knative_eventing.sources_knative_dev.v1alpha1",
        "IntegrationSource",
    ),
    ("IntegrationSource", ""): (
        "cloudcoil.models.knative_eventing.sources_knative_dev.v1alpha1",
        "IntegrationSource",
    ),
    ("JobSink", "sinks.knative.dev/v1alpha1"): (
        "cloudcoil.models.knative_eventing.sinks_knative_dev.v1alpha1",
        "JobSink",
    ),
    ("JobSink", ""): ("cloudcoil.models.knative_eventing.sinks_knative_dev.v1alpha1", "JobSink"),
    ("Parallel", "flows.knative.dev/v1"): (
        "cloudcoil.models.knative_eventing.flows_knative_dev.v1",
        "Parallel",
    ),
    ("Parallel", ""): ("cloudcoil.models.knative_eventing.flows_knative_dev.v1", "Parallel"),
    ("PingSource", "sources.knative.dev/v1"): (
        "cloudcoil.models.knative_eventing.sources_knative_dev.v1",
        "PingSource",
    ),
    ("PingSource", "sources.knative.dev/v1beta2"): (
        "cloudcoil.models.knative_eventing.sources_knative_dev.v1beta2",
        "PingSource",
    ),
    ("RequestReply", "eventing.knative.dev/v1alpha1"): (
        "cloudcoil.models.knative_eventing.eventing_knative_dev.v1alpha1",
        "RequestReply",
    ),
    ("RequestReply", ""): (
        "cloudcoil.models.knative_eventing.eventing_knative_dev.v1alpha1",
        "RequestReply",
    ),
    ("Sequence", "flows.knative.dev/v1"): (
        "cloudcoil.models.knative_eventing.flows_knative_dev.v1",
        "Sequence",
    ),
    ("Sequence", ""): ("cloudcoil.models.knative_eventing.flows_knative_dev.v1", "Sequence"),
    ("SinkBinding", "sources.knative.dev/v1"): (
        "cloudcoil.models.knative_eventing.sources_knative_dev.v1",
        "SinkBinding",
    ),
    ("SinkBinding", ""): (
        "cloudcoil.models.knative_eventing.sources_knative_dev.v1",
        "SinkBinding",
    ),
    ("Subscription", "messaging.knative.dev/v1"): (
        "cloudcoil.models.knative_eventing.messaging_knative_dev.v1",
        "Subscription",
    ),
    ("Subscription", ""): (
        "cloudcoil.models.knative_eventing.messaging_knative_dev.v1",
        "Subscription",
    ),
    ("Trigger", "eventing.knative.dev/v1"): (
        "cloudcoil.models.knative_eventing.eventing_knative_dev.v1",
        "Trigger",
    ),
    ("Trigger", ""): ("cloudcoil.models.knative_eventing.eventing_knative_dev.v1", "Trigger"),
}


@overload
def get_model(
    kind: Literal["ApiServerSource"], *, api_version: Literal["sources.knative.dev/v1"]
) -> type[_Resource0]: ...


@overload
def get_model(
    kind: Literal["ApiServerSource"], *, api_version: Literal[""] = ""
) -> type[_Resource0]: ...


@overload
def get_model(
    kind: Literal["Broker"], *, api_version: Literal["eventing.knative.dev/v1"]
) -> type[_Resource1]: ...


@overload
def get_model(kind: Literal["Broker"], *, api_version: Literal[""] = "") -> type[_Resource1]: ...


@overload
def get_model(
    kind: Literal["Channel"], *, api_version: Literal["messaging.knative.dev/v1"]
) -> type[_Resource2]: ...


@overload
def get_model(kind: Literal["Channel"], *, api_version: Literal[""] = "") -> type[_Resource2]: ...


@overload
def get_model(
    kind: Literal["ContainerSource"], *, api_version: Literal["sources.knative.dev/v1"]
) -> type[_Resource3]: ...


@overload
def get_model(
    kind: Literal["ContainerSource"], *, api_version: Literal[""] = ""
) -> type[_Resource3]: ...


@overload
def get_model(
    kind: Literal["EventPolicy"], *, api_version: Literal["eventing.knative.dev/v1alpha1"]
) -> type[_Resource4]: ...


@overload
def get_model(
    kind: Literal["EventPolicy"], *, api_version: Literal[""] = ""
) -> type[_Resource4]: ...


@overload
def get_model(
    kind: Literal["EventTransform"], *, api_version: Literal["eventing.knative.dev/v1alpha1"]
) -> type[_Resource5]: ...


@overload
def get_model(
    kind: Literal["EventTransform"], *, api_version: Literal[""] = ""
) -> type[_Resource5]: ...


@overload
def get_model(
    kind: Literal["EventType"], *, api_version: Literal["eventing.knative.dev/v1beta1"]
) -> type[_Resource6]: ...


@overload
def get_model(
    kind: Literal["EventType"], *, api_version: Literal["eventing.knative.dev/v1beta2"]
) -> type[_Resource7]: ...


@overload
def get_model(
    kind: Literal["EventType"], *, api_version: Literal["eventing.knative.dev/v1beta3"]
) -> type[_Resource8]: ...


@overload
def get_model(
    kind: Literal["IntegrationSink"], *, api_version: Literal["sinks.knative.dev/v1alpha1"]
) -> type[_Resource9]: ...


@overload
def get_model(
    kind: Literal["IntegrationSink"], *, api_version: Literal[""] = ""
) -> type[_Resource9]: ...


@overload
def get_model(
    kind: Literal["IntegrationSource"], *, api_version: Literal["sources.knative.dev/v1alpha1"]
) -> type[_Resource10]: ...


@overload
def get_model(
    kind: Literal["IntegrationSource"], *, api_version: Literal[""] = ""
) -> type[_Resource10]: ...


@overload
def get_model(
    kind: Literal["JobSink"], *, api_version: Literal["sinks.knative.dev/v1alpha1"]
) -> type[_Resource11]: ...


@overload
def get_model(kind: Literal["JobSink"], *, api_version: Literal[""] = "") -> type[_Resource11]: ...


@overload
def get_model(
    kind: Literal["Parallel"], *, api_version: Literal["flows.knative.dev/v1"]
) -> type[_Resource12]: ...


@overload
def get_model(kind: Literal["Parallel"], *, api_version: Literal[""] = "") -> type[_Resource12]: ...


@overload
def get_model(
    kind: Literal["PingSource"], *, api_version: Literal["sources.knative.dev/v1"]
) -> type[_Resource13]: ...


@overload
def get_model(
    kind: Literal["PingSource"], *, api_version: Literal["sources.knative.dev/v1beta2"]
) -> type[_Resource14]: ...


@overload
def get_model(
    kind: Literal["RequestReply"], *, api_version: Literal["eventing.knative.dev/v1alpha1"]
) -> type[_Resource15]: ...


@overload
def get_model(
    kind: Literal["RequestReply"], *, api_version: Literal[""] = ""
) -> type[_Resource15]: ...


@overload
def get_model(
    kind: Literal["Sequence"], *, api_version: Literal["flows.knative.dev/v1"]
) -> type[_Resource16]: ...


@overload
def get_model(kind: Literal["Sequence"], *, api_version: Literal[""] = "") -> type[_Resource16]: ...


@overload
def get_model(
    kind: Literal["SinkBinding"], *, api_version: Literal["sources.knative.dev/v1"]
) -> type[_Resource17]: ...


@overload
def get_model(
    kind: Literal["SinkBinding"], *, api_version: Literal[""] = ""
) -> type[_Resource17]: ...


@overload
def get_model(
    kind: Literal["Subscription"], *, api_version: Literal["messaging.knative.dev/v1"]
) -> type[_Resource18]: ...


@overload
def get_model(
    kind: Literal["Subscription"], *, api_version: Literal[""] = ""
) -> type[_Resource18]: ...


@overload
def get_model(
    kind: Literal["Trigger"], *, api_version: Literal["eventing.knative.dev/v1"]
) -> type[_Resource19]: ...


@overload
def get_model(kind: Literal["Trigger"], *, api_version: Literal[""] = "") -> type[_Resource19]: ...


@overload
def get_model(kind: str, *, api_version: str = "") -> type[Resource]: ...


def get_model(kind: str, *, api_version: str = "") -> type[Resource]:
    """Look up a model in this package; specify api_version for ambiguous kinds."""
    try:
        module, name = _MODELS[kind, api_version]
    except KeyError:
        raise ValueError(
            f"Unknown or ambiguous resource {kind!r}; specify a supported api_version"
        ) from None
    return getattr(import_module(module), name)
