# Generated by cloudcoil-model-codegen v0.7.1
# DO NOT EDIT

from typing import (
    Annotated,
    Any,
    Callable,
    ClassVar,
    Literal,
    overload,
)

from cloudcoil.apimachinery import ObjectMeta
from cloudcoil.pydantic import (
    UNSET,
    BaseModel,
    BaseModelBuilder,
    BuilderContextBase,
    GenericListBuilder,
    ListBuilderContext,
    Never,
    Self,
)
from cloudcoil.resources import Resource
from pydantic import Field


class EventTypeSpecReference(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["EventTypeSpecReference"]:
            return EventTypeSpecReference

        def build(self) -> "EventTypeSpecReference":
            return EventTypeSpecReference(**self._attrs)

        def api_version(self, value: str | None, /) -> Self:
            "API version of the referent."
            return self._set("api_version", value)

        def kind(self, value: str | None, /) -> Self:
            "Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        def name(self, value: str | None, /) -> Self:
            "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
            return self._set("name", value)

        def namespace(self, value: str | None, /) -> Self:
            "Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/ This is an optional field, it gets defaulted to the object holding it if left out."
            return self._set("namespace", value)

        def address(self, value: str | None, /) -> Self:
            "Address points to a specific Address Name"
            return self._set("address", value)

    class BuilderContext(BuilderContextBase["EventTypeSpecReference.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = EventTypeSpecReference.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for EventTypeSpecReference."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["EventTypeSpecReference", Builder]:
        return GenericListBuilder[EventTypeSpecReference, EventTypeSpecReference.Builder]()

    api_version: Annotated[str | None, Field(alias="apiVersion")] = None
    "API version of the referent."
    kind: str | None = None
    "Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    name: str | None = None
    "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
    namespace: str | None = None
    "Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/ This is an optional field, it gets defaulted to the object holding it if left out."
    address: str | None = None
    "Address points to a specific Address Name"


class EventTypeStatusConditionsItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["EventTypeStatusConditionsItem"]:
            return EventTypeStatusConditionsItem

        def build(self) -> "EventTypeStatusConditionsItem":
            return EventTypeStatusConditionsItem(**self._attrs)

        def last_transition_time(self, value: str | None, /) -> Self:
            "LastTransitionTime is the last time the condition transitioned from one status to another. We use VolatileTime in place of metav1.Time to exclude this from creating equality.Semantic differences (all other things held constant)."
            return self._set("last_transition_time", value)

        def message(self, value: str | None, /) -> Self:
            "A human readable message indicating details about the transition."
            return self._set("message", value)

        def reason(self, value: str | None, /) -> Self:
            "The reason for the condition\u0027s last transition."
            return self._set("reason", value)

        def severity(self, value: str | None, /) -> Self:
            "Severity with which to treat failures of this type of condition. When this is not specified, it defaults to Error."
            return self._set("severity", value)

        def status(self, value: str, /) -> Self:
            "Status of the condition, one of True, False, Unknown."
            return self._set("status", value)

        def type(self, value: str, /) -> Self:
            "Type of condition."
            return self._set("type", value)

    class BuilderContext(BuilderContextBase["EventTypeStatusConditionsItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = EventTypeStatusConditionsItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for EventTypeStatusConditionsItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["EventTypeStatusConditionsItem", Builder]:
        return GenericListBuilder[
            EventTypeStatusConditionsItem, EventTypeStatusConditionsItem.Builder
        ]()

    last_transition_time: Annotated[str | None, Field(alias="lastTransitionTime")] = None
    "LastTransitionTime is the last time the condition transitioned from one status to another. We use VolatileTime in place of metav1.Time to exclude this from creating equality.Semantic differences (all other things held constant)."
    message: str | None = None
    "A human readable message indicating details about the transition."
    reason: str | None = None
    "The reason for the condition\u0027s last transition."
    severity: str | None = None
    "Severity with which to treat failures of this type of condition. When this is not specified, it defaults to Error."
    status: str
    "Status of the condition, one of True, False, Unknown."
    type: str
    "Type of condition."


class EventTypeSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["EventTypeSpec"]:
            return EventTypeSpec

        def build(self) -> "EventTypeSpec":
            return EventTypeSpec(**self._attrs)

        def broker(self, value: str | None, /) -> Self:
            return self._set("broker", value)

        @overload
        def reference(
            self, value_or_callback: EventTypeSpecReference | None, /
        ) -> "EventTypeSpec.Builder": ...

        @overload
        def reference(
            self,
            value_or_callback: Callable[
                [EventTypeSpecReference.Builder],
                EventTypeSpecReference.Builder | EventTypeSpecReference,
            ],
            /,
        ) -> "EventTypeSpec.Builder": ...

        @overload
        def reference(
            self, value_or_callback: Never = ...
        ) -> "EventTypeSpecReference.BuilderContext": ...

        def reference(self, value_or_callback=UNSET, /):
            "Reference a resource. For example, Broker."
            if self._in_context and value_or_callback is UNSET:
                context = EventTypeSpecReference.BuilderContext()
                context._parent_builder = self
                context._field_name = "reference"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(EventTypeSpecReference.builder())
                if isinstance(output, EventTypeSpecReference.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("reference", value)

        def description(self, value: str | None, /) -> Self:
            "Description is an optional field used to describe the EventType, in any meaningful way."
            return self._set("description", value)

        def schema_(self, value: str | None, /) -> Self:
            "Schema is a URI, it represents the CloudEvents schemaurl extension attribute. It may be a JSON schema, a protobuf schema, etc. It is optional."
            return self._set("schema_", value)

        def schema_data(self, value: str | None, /) -> Self:
            "SchemaData allows the CloudEvents schema to be stored directly in the EventType. Content is dependent on the encoding. Optional attribute. The contents are not validated or manipulated by the system."
            return self._set("schema_data", value)

        def source(self, value: str | None, /) -> Self:
            "Source is a URI, it represents the CloudEvents source."
            return self._set("source", value)

        def type(self, value: str | None, /) -> Self:
            "Type represents the CloudEvents type. It is authoritative."
            return self._set("type", value)

    class BuilderContext(BuilderContextBase["EventTypeSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = EventTypeSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for EventTypeSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["EventTypeSpec", Builder]:
        return GenericListBuilder[EventTypeSpec, EventTypeSpec.Builder]()

    broker: str | None = None
    reference: EventTypeSpecReference | None = None
    "Reference a resource. For example, Broker."
    description: str | None = None
    "Description is an optional field used to describe the EventType, in any meaningful way."
    schema_: Annotated[str | None, Field(alias="schema")] = None
    "Schema is a URI, it represents the CloudEvents schemaurl extension attribute. It may be a JSON schema, a protobuf schema, etc. It is optional."
    schema_data: Annotated[str | None, Field(alias="schemaData")] = None
    "SchemaData allows the CloudEvents schema to be stored directly in the EventType. Content is dependent on the encoding. Optional attribute. The contents are not validated or manipulated by the system."
    source: str | None = None
    "Source is a URI, it represents the CloudEvents source."
    type: str | None = None
    "Type represents the CloudEvents type. It is authoritative."


class EventTypeStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["EventTypeStatus"]:
            return EventTypeStatus

        def build(self) -> "EventTypeStatus":
            return EventTypeStatus(**self._attrs)

        def annotations(self, value: dict[str, Any] | None, /) -> Self:
            "Annotations is additional Status fields for the Resource to save some additional State as well as convey more information to the user. This is roughly akin to Annotations on any k8s resource, just the reconciler conveying richer information outwards."
            return self._set("annotations", value)

        @overload
        def conditions(
            self, value_or_callback: list[EventTypeStatusConditionsItem] | None, /
        ) -> "EventTypeStatus.Builder": ...

        @overload
        def conditions(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        EventTypeStatusConditionsItem,
                        EventTypeStatusConditionsItem.Builder,
                    ]
                ],
                GenericListBuilder[
                    EventTypeStatusConditionsItem, EventTypeStatusConditionsItem.Builder
                ]
                | list[EventTypeStatusConditionsItem],
            ],
            /,
        ) -> "EventTypeStatus.Builder": ...

        @overload
        def conditions(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[EventTypeStatusConditionsItem.Builder]: ...

        def conditions(self, value_or_callback=UNSET, /):
            "Conditions the latest available observations of a resource\u0027s current state."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[EventTypeStatusConditionsItem.Builder]()
                context._parent_builder = self
                context._field_name = "conditions"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(EventTypeStatusConditionsItem.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("conditions", value)

        def observed_generation(self, value: int | None, /) -> Self:
            "ObservedGeneration is the \u0027Generation\u0027 of the Service that was last processed by the controller."
            return self._set("observed_generation", value)

    class BuilderContext(BuilderContextBase["EventTypeStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = EventTypeStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for EventTypeStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["EventTypeStatus", Builder]:
        return GenericListBuilder[EventTypeStatus, EventTypeStatus.Builder]()

    annotations: dict[str, Any] | None = None
    "Annotations is additional Status fields for the Resource to save some additional State as well as convey more information to the user. This is roughly akin to Annotations on any k8s resource, just the reconciler conveying richer information outwards."
    conditions: list[EventTypeStatusConditionsItem] | None = None
    "Conditions the latest available observations of a resource\u0027s current state."
    observed_generation: Annotated[int | None, Field(alias="observedGeneration")] = None
    "ObservedGeneration is the \u0027Generation\u0027 of the Service that was last processed by the controller."


class EventType(Resource):
    __cloudcoil_api__: ClassVar[dict] = {
        "plural": "eventtypes",
        "scope": "Namespaced",
        "status": True,
    }

    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["EventType"]:
            return EventType

        def build(self) -> "EventType":
            return EventType(**self._attrs)

        @overload
        def spec(self, value_or_callback: EventTypeSpec | None, /) -> "EventType.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[
                [EventTypeSpec.Builder], EventTypeSpec.Builder | EventTypeSpec
            ],
            /,
        ) -> "EventType.Builder": ...

        @overload
        def spec(self, value_or_callback: Never = ...) -> "EventTypeSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = EventTypeSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(EventTypeSpec.builder())
                if isinstance(output, EventTypeSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

        @overload
        def status(self, value_or_callback: EventTypeStatus | None, /) -> "EventType.Builder": ...

        @overload
        def status(
            self,
            value_or_callback: Callable[
                [EventTypeStatus.Builder], EventTypeStatus.Builder | EventTypeStatus
            ],
            /,
        ) -> "EventType.Builder": ...

        @overload
        def status(self, value_or_callback: Never = ...) -> "EventTypeStatus.BuilderContext": ...

        def status(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = EventTypeStatus.BuilderContext()
                context._parent_builder = self
                context._field_name = "status"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(EventTypeStatus.builder())
                if isinstance(output, EventTypeStatus.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("status", value)

        def api_version(self, value: Literal["eventing.knative.dev/v1beta2"], /) -> Self:
            return self._set("api_version", value)

        def kind(self, value: Literal["EventType"], /) -> Self:
            return self._set("kind", value)

        @overload
        def metadata(self, value_or_callback: ObjectMeta | None, /) -> "EventType.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "EventType.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

    class BuilderContext(BuilderContextBase["EventType.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = EventType.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for EventType."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["EventType", Builder]:
        return GenericListBuilder[EventType, EventType.Builder]()

    spec: EventTypeSpec | None = None
    status: EventTypeStatus | None = None
    api_version: Annotated[Literal["eventing.knative.dev/v1beta2"], Field(alias="apiVersion")] = (
        "eventing.knative.dev/v1beta2"
    )
    kind: Literal["EventType"] = "EventType"
    metadata: ObjectMeta | None = None
