# Generated by cloudcoil-model-codegen v0.7.1
# DO NOT EDIT

from typing import (
    Annotated,
    Any,
    Callable,
    ClassVar,
    Literal,
    overload,
)

from cloudcoil.apimachinery import ObjectMeta
from cloudcoil.pydantic import (
    UNSET,
    BaseModel,
    BaseModelBuilder,
    BuilderContextBase,
    GenericListBuilder,
    ListBuilderContext,
    Never,
    Self,
)
from cloudcoil.resources import Resource
from pydantic import Field


class JobSinkSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["JobSinkSpec"]:
            return JobSinkSpec

        def build(self) -> "JobSinkSpec":
            return JobSinkSpec(**self._attrs)

        def job(self, value: dict[str, Any] | None, /) -> Self:
            "Full Job resource object, see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#job-v1-batch for more details."
            return self._set("job", value)

    class BuilderContext(BuilderContextBase["JobSinkSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = JobSinkSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for JobSinkSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["JobSinkSpec", Builder]:
        return GenericListBuilder[JobSinkSpec, JobSinkSpec.Builder]()

    job: dict[str, Any] | None = None
    "Full Job resource object, see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#job-v1-batch for more details."


class IntegrationSinkSpecLog(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSinkSpecLog"]:
            return IntegrationSinkSpecLog

        def build(self) -> "IntegrationSinkSpecLog":
            return IntegrationSinkSpecLog(**self._attrs)

        def logger_name(self, value: str | None, /) -> Self:
            "Name of the logging category to use"
            return self._set("logger_name", value)

        def level(self, value: str | None, /) -> Self:
            "Logging level to use"
            return self._set("level", value)

        def log_mask(self, value: bool | None, /) -> Self:
            "Mask sensitive information like password or passphrase in the log"
            return self._set("log_mask", value)

        def marker(self, value: str | None, /) -> Self:
            "An optional Marker name to use"
            return self._set("marker", value)

        def multiline(self, value: bool | None, /) -> Self:
            "If enabled then each information is outputted on a newline"
            return self._set("multiline", value)

        def show_all_properties(self, value: bool | None, /) -> Self:
            "Show all of the exchange properties (both internal and custom)"
            return self._set("show_all_properties", value)

        def show_body(self, value: bool | None, /) -> Self:
            "Show the message body"
            return self._set("show_body", value)

        def show_body_type(self, value: bool | None, /) -> Self:
            "Show the body Java type"
            return self._set("show_body_type", value)

        def show_exchange_pattern(self, value: bool | None, /) -> Self:
            "Shows the Message Exchange Pattern (or MEP for short)"
            return self._set("show_exchange_pattern", value)

        def show_headers(self, value: bool | None, /) -> Self:
            "Show the headers received"
            return self._set("show_headers", value)

        def show_properties(self, value: bool | None, /) -> Self:
            "Show the exchange properties (only custom). Use showAllProperties to show both internal and custom properties."
            return self._set("show_properties", value)

        def show_streams(self, value: bool | None, /) -> Self:
            "Show the stream bodies (they may not be available in following steps)"
            return self._set("show_streams", value)

        def show_cached_streams(self, value: bool | None, /) -> Self:
            "Whether Camel should show cached stream bodies or not."
            return self._set("show_cached_streams", value)

    class BuilderContext(BuilderContextBase["IntegrationSinkSpecLog.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSinkSpecLog.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSinkSpecLog."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["IntegrationSinkSpecLog", Builder]:
        return GenericListBuilder[IntegrationSinkSpecLog, IntegrationSinkSpecLog.Builder]()

    logger_name: Annotated[str | None, Field(alias="loggerName", title="Logger Name")] = "log-sink"
    "Name of the logging category to use"
    level: Annotated[str | None, Field(title="Log Level")] = "INFO"
    "Logging level to use"
    log_mask: Annotated[bool | None, Field(alias="logMask", title="Log Mask")] = False
    "Mask sensitive information like password or passphrase in the log"
    marker: Annotated[str | None, Field(title="Marker")] = None
    "An optional Marker name to use"
    multiline: Annotated[bool | None, Field(title="Multiline")] = False
    "If enabled then each information is outputted on a newline"
    show_all_properties: Annotated[
        bool | None, Field(alias="showAllProperties", title="Show All Properties")
    ] = False
    "Show all of the exchange properties (both internal and custom)"
    show_body: Annotated[bool | None, Field(alias="showBody", title="Show Body")] = True
    "Show the message body"
    show_body_type: Annotated[bool | None, Field(alias="showBodyType", title="Show Body Type")] = (
        True
    )
    "Show the body Java type"
    show_exchange_pattern: Annotated[
        bool | None, Field(alias="showExchangePattern", title="Show Exchange Pattern")
    ] = True
    "Shows the Message Exchange Pattern (or MEP for short)"
    show_headers: Annotated[bool | None, Field(alias="showHeaders", title="Show Headers")] = False
    "Show the headers received"
    show_properties: Annotated[
        bool | None, Field(alias="showProperties", title="Show Properties")
    ] = False
    "Show the exchange properties (only custom). Use showAllProperties to show both internal and custom properties."
    show_streams: Annotated[bool | None, Field(alias="showStreams", title="Show Streams")] = False
    "Show the stream bodies (they may not be available in following steps)"
    show_cached_streams: Annotated[
        bool | None, Field(alias="showCachedStreams", title="Show Cached Streams")
    ] = True
    "Whether Camel should show cached stream bodies or not."


class IntegrationSinkSpecAwsS3(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSinkSpecAwsS3"]:
            return IntegrationSinkSpecAwsS3

        def build(self) -> "IntegrationSinkSpecAwsS3":
            return IntegrationSinkSpecAwsS3(**self._attrs)

        def arn(self, value: str | None, /) -> Self:
            "The S3 Bucket name or Amazon Resource Name (ARN)."
            return self._set("arn", value)

        def delete_after_read(self, value: bool | None, /) -> Self:
            "Specifies to delete objects after consuming them."
            return self._set("delete_after_read", value)

        def move_after_read(self, value: bool | None, /) -> Self:
            "Move objects from S3 bucket to a different bucket after they have been retrieved."
            return self._set("move_after_read", value)

        def destination_bucket(self, value: str | None, /) -> Self:
            "Define the destination bucket where an object must be moved when moveAfterRead is set to true."
            return self._set("destination_bucket", value)

        def destination_bucket_prefix(self, value: str | None, /) -> Self:
            "Define the destination bucket prefix to use when an object must be moved, and moveAfterRead is set to true."
            return self._set("destination_bucket_prefix", value)

        def destination_bucket_suffix(self, value: str | None, /) -> Self:
            "Define the destination bucket suffix to use when an object must be moved, and moveAfterRead is set to true."
            return self._set("destination_bucket_suffix", value)

        def region(self, value: str | None, /) -> Self:
            "The AWS region to access."
            return self._set("region", value)

        def auto_create_bucket(self, value: bool | None, /) -> Self:
            "Specifies to automatically create the S3 bucket."
            return self._set("auto_create_bucket", value)

        def prefix(self, value: str | None, /) -> Self:
            "The AWS S3 bucket prefix to consider while searching."
            return self._set("prefix", value)

        def ignore_body(self, value: bool | None, /) -> Self:
            "If true, the S3 Object body is ignored. Setting this to true overrides any behavior defined by the `includeBody` option. If false, the S3 object is put in the body."
            return self._set("ignore_body", value)

        def uri_endpoint_override(self, value: str | None, /) -> Self:
            "The overriding endpoint URI. To use this option, you must also select the `overrideEndpoint` option."
            return self._set("uri_endpoint_override", value)

        def override_endpoint(self, value: bool | None, /) -> Self:
            "Select this option to override the endpoint URI. To use this option, you must also provide a URI for the `uriEndpointOverride` option."
            return self._set("override_endpoint", value)

        def force_path_style(self, value: bool | None, /) -> Self:
            "Forces path style when accessing AWS S3 buckets."
            return self._set("force_path_style", value)

        def delay(self, value: int | None, /) -> Self:
            "The number of milliseconds before the next poll of the selected bucket."
            return self._set("delay", value)

        def max_messages_per_poll(self, value: int | None, /) -> Self:
            "Gets the maximum number of messages as a limit to poll at each polling. Gets the maximum number of messages as a limit to poll at each polling. The default value is 10. Use 0 or a negative number to set it as unlimited."
            return self._set("max_messages_per_poll", value)

    class BuilderContext(BuilderContextBase["IntegrationSinkSpecAwsS3.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSinkSpecAwsS3.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSinkSpecAwsS3."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["IntegrationSinkSpecAwsS3", Builder]:
        return GenericListBuilder[IntegrationSinkSpecAwsS3, IntegrationSinkSpecAwsS3.Builder]()

    arn: Annotated[str | None, Field(title="Bucket Name")] = None
    "The S3 Bucket name or Amazon Resource Name (ARN)."
    delete_after_read: Annotated[
        bool | None, Field(alias="deleteAfterRead", title="Auto-delete Objects")
    ] = True
    "Specifies to delete objects after consuming them."
    move_after_read: Annotated[
        bool | None, Field(alias="moveAfterRead", title="Move Objects After Delete")
    ] = False
    "Move objects from S3 bucket to a different bucket after they have been retrieved."
    destination_bucket: Annotated[
        str | None, Field(alias="destinationBucket", title="Destination Bucket")
    ] = None
    "Define the destination bucket where an object must be moved when moveAfterRead is set to true."
    destination_bucket_prefix: Annotated[
        str | None,
        Field(alias="destinationBucketPrefix", title="Destination Bucket Prefix"),
    ] = None
    "Define the destination bucket prefix to use when an object must be moved, and moveAfterRead is set to true."
    destination_bucket_suffix: Annotated[
        str | None,
        Field(alias="destinationBucketSuffix", title="Destination Bucket Suffix"),
    ] = None
    "Define the destination bucket suffix to use when an object must be moved, and moveAfterRead is set to true."
    region: Annotated[str | None, Field(title="AWS Region")] = None
    "The AWS region to access."
    auto_create_bucket: Annotated[
        bool | None, Field(alias="autoCreateBucket", title="Autocreate Bucket")
    ] = False
    "Specifies to automatically create the S3 bucket."
    prefix: Annotated[str | None, Field(examples=["folder/"], title="Prefix")] = None
    "The AWS S3 bucket prefix to consider while searching."
    ignore_body: Annotated[bool | None, Field(alias="ignoreBody", title="Ignore Body")] = False
    "If true, the S3 Object body is ignored. Setting this to true overrides any behavior defined by the `includeBody` option. If false, the S3 object is put in the body."
    uri_endpoint_override: Annotated[
        str | None, Field(alias="uriEndpointOverride", title="Overwrite Endpoint URI")
    ] = None
    "The overriding endpoint URI. To use this option, you must also select the `overrideEndpoint` option."
    override_endpoint: Annotated[
        bool | None, Field(alias="overrideEndpoint", title="Endpoint Overwrite")
    ] = False
    "Select this option to override the endpoint URI. To use this option, you must also provide a URI for the `uriEndpointOverride` option."
    force_path_style: Annotated[
        bool | None, Field(alias="forcePathStyle", title="Force Path Style")
    ] = False
    "Forces path style when accessing AWS S3 buckets."
    delay: Annotated[int | None, Field(title="Delay")] = 500
    "The number of milliseconds before the next poll of the selected bucket."
    max_messages_per_poll: Annotated[
        int | None, Field(alias="maxMessagesPerPoll", title="Max Messages Per Poll")
    ] = 10
    "Gets the maximum number of messages as a limit to poll at each polling. Gets the maximum number of messages as a limit to poll at each polling. The default value is 10. Use 0 or a negative number to set it as unlimited."


class IntegrationSinkSpecAwsSqs(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSinkSpecAwsSqs"]:
            return IntegrationSinkSpecAwsSqs

        def build(self) -> "IntegrationSinkSpecAwsSqs":
            return IntegrationSinkSpecAwsSqs(**self._attrs)

        def arn(self, value: str | None, /) -> Self:
            "The SQS Queue Name or ARN"
            return self._set("arn", value)

        def delete_after_read(self, value: bool | None, /) -> Self:
            "Delete messages after consuming them"
            return self._set("delete_after_read", value)

        def region(self, value: str | None, /) -> Self:
            "The AWS region to access."
            return self._set("region", value)

        def auto_create_queue(self, value: bool | None, /) -> Self:
            "Setting the autocreation of the SQS queue."
            return self._set("auto_create_queue", value)

        def host(self, value: str | None, /) -> Self:
            "The hostname of the Amazon AWS cloud."
            return self._set("host", value)

        def protocol(self, value: str | None, /) -> Self:
            "The underlying protocol used to communicate with SQS"
            return self._set("protocol", value)

        def queue_url(self, value: str | None, /) -> Self:
            "The full SQS Queue URL (required if using KEDA)"
            return self._set("queue_url", value)

        def uri_endpoint_override(self, value: str | None, /) -> Self:
            "The overriding endpoint URI. To use this option, you must also select the `overrideEndpoint` option."
            return self._set("uri_endpoint_override", value)

        def override_endpoint(self, value: bool | None, /) -> Self:
            "Select this option to override the endpoint URI. To use this option, you must also provide a URI for the `uriEndpointOverride` option."
            return self._set("override_endpoint", value)

        def delay(self, value: int | None, /) -> Self:
            "The number of milliseconds before the next poll of the selected stream"
            return self._set("delay", value)

        def greedy(self, value: bool | None, /) -> Self:
            "If greedy is enabled, then the polling will happen immediately again, if the previous run polled 1 or more messages."
            return self._set("greedy", value)

        def max_messages_per_poll(self, value: int | None, /) -> Self:
            "The maximum number of messages to return. Amazon SQS never returns more messages than this value (however, fewer messages might be returned). Valid values 1 to 10. Default 1."
            return self._set("max_messages_per_poll", value)

        def wait_time_seconds(self, value: int | None, /) -> Self:
            "The duration (in seconds) for which the call waits for a message to arrive in the queue before returning. If a message is available, the call returns sooner than WaitTimeSeconds. If no messages are available and the wait time expires, the call does not return a message list."
            return self._set("wait_time_seconds", value)

        def visibility_timeout(self, value: int | None, /) -> Self:
            "The duration (in seconds) that the received messages are hidden from subsequent retrieve requests after being retrieved by a ReceiveMessage request."
            return self._set("visibility_timeout", value)

    class BuilderContext(BuilderContextBase["IntegrationSinkSpecAwsSqs.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSinkSpecAwsSqs.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSinkSpecAwsSqs."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["IntegrationSinkSpecAwsSqs", Builder]:
        return GenericListBuilder[IntegrationSinkSpecAwsSqs, IntegrationSinkSpecAwsSqs.Builder]()

    arn: Annotated[str | None, Field(title="Queue Name")] = None
    "The SQS Queue Name or ARN"
    delete_after_read: Annotated[
        bool | None, Field(alias="deleteAfterRead", title="Auto-delete Messages")
    ] = True
    "Delete messages after consuming them"
    region: Annotated[str | None, Field(title="AWS Region")] = None
    "The AWS region to access."
    auto_create_queue: Annotated[
        bool | None, Field(alias="autoCreateQueue", title="Autocreate Queue")
    ] = False
    "Setting the autocreation of the SQS queue."
    host: Annotated[str | None, Field(title="AWS Host")] = "amazonaws.com"
    "The hostname of the Amazon AWS cloud."
    protocol: Annotated[str | None, Field(examples=["http or https"], title="Protocol")] = "https"
    "The underlying protocol used to communicate with SQS"
    queue_url: Annotated[str | None, Field(alias="queueURL", title="Queue URL")] = None
    "The full SQS Queue URL (required if using KEDA)"
    uri_endpoint_override: Annotated[
        str | None, Field(alias="uriEndpointOverride", title="Overwrite Endpoint URI")
    ] = None
    "The overriding endpoint URI. To use this option, you must also select the `overrideEndpoint` option."
    override_endpoint: Annotated[
        bool | None, Field(alias="overrideEndpoint", title="Endpoint Overwrite")
    ] = False
    "Select this option to override the endpoint URI. To use this option, you must also provide a URI for the `uriEndpointOverride` option."
    delay: Annotated[int | None, Field(title="Delay")] = 500
    "The number of milliseconds before the next poll of the selected stream"
    greedy: Annotated[bool | None, Field(title="Greedy Scheduler")] = False
    "If greedy is enabled, then the polling will happen immediately again, if the previous run polled 1 or more messages."
    max_messages_per_poll: Annotated[
        int | None, Field(alias="maxMessagesPerPoll", title="Max Messages Per Poll")
    ] = 1
    "The maximum number of messages to return. Amazon SQS never returns more messages than this value (however, fewer messages might be returned). Valid values 1 to 10. Default 1."
    wait_time_seconds: Annotated[
        int | None, Field(alias="waitTimeSeconds", title="Wait Time Seconds")
    ] = None
    "The duration (in seconds) for which the call waits for a message to arrive in the queue before returning. If a message is available, the call returns sooner than WaitTimeSeconds. If no messages are available and the wait time expires, the call does not return a message list."
    visibility_timeout: Annotated[
        int | None, Field(alias="visibilityTimeout", title="Visibility Timeout")
    ] = None
    "The duration (in seconds) that the received messages are hidden from subsequent retrieve requests after being retrieved by a ReceiveMessage request."


class IntegrationSinkSpecAwsSns(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSinkSpecAwsSns"]:
            return IntegrationSinkSpecAwsSns

        def build(self) -> "IntegrationSinkSpecAwsSns":
            return IntegrationSinkSpecAwsSns(**self._attrs)

        def arn(self, value: str | None, /) -> Self:
            "The SNS topic name name or Amazon Resource Name (ARN)."
            return self._set("arn", value)

        def region(self, value: str | None, /) -> Self:
            "The AWS region to access."
            return self._set("region", value)

        def auto_create_topic(self, value: bool | None, /) -> Self:
            "Setting the autocreation of the SNS topic."
            return self._set("auto_create_topic", value)

        def uri_endpoint_override(self, value: str | None, /) -> Self:
            "The overriding endpoint URI. To use this option, you must also select the `overrideEndpoint` option."
            return self._set("uri_endpoint_override", value)

        def override_endpoint(self, value: bool | None, /) -> Self:
            "Select this option to override the endpoint URI. To use this option, you must also provide a URI for the `uriEndpointOverride` option."
            return self._set("override_endpoint", value)

    class BuilderContext(BuilderContextBase["IntegrationSinkSpecAwsSns.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSinkSpecAwsSns.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSinkSpecAwsSns."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["IntegrationSinkSpecAwsSns", Builder]:
        return GenericListBuilder[IntegrationSinkSpecAwsSns, IntegrationSinkSpecAwsSns.Builder]()

    arn: Annotated[str | None, Field(title="Topic Name")] = None
    "The SNS topic name name or Amazon Resource Name (ARN)."
    region: Annotated[str | None, Field(title="AWS Region")] = None
    "The AWS region to access."
    auto_create_topic: Annotated[
        bool | None, Field(alias="autoCreateTopic", title="Autocreate Topic")
    ] = False
    "Setting the autocreation of the SNS topic."
    uri_endpoint_override: Annotated[
        str | None, Field(alias="uriEndpointOverride", title="Overwrite Endpoint URI")
    ] = None
    "The overriding endpoint URI. To use this option, you must also select the `overrideEndpoint` option."
    override_endpoint: Annotated[
        bool | None, Field(alias="overrideEndpoint", title="Endpoint Overwrite")
    ] = False
    "Select this option to override the endpoint URI. To use this option, you must also provide a URI for the `uriEndpointOverride` option."


class IntegrationSinkSpecAwsAuthSecretRef(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSinkSpecAwsAuthSecretRef"]:
            return IntegrationSinkSpecAwsAuthSecretRef

        def build(self) -> "IntegrationSinkSpecAwsAuthSecretRef":
            return IntegrationSinkSpecAwsAuthSecretRef(**self._attrs)

        def name(self, value: str, /) -> Self:
            "Secret name"
            return self._set("name", value)

    class BuilderContext(BuilderContextBase["IntegrationSinkSpecAwsAuthSecretRef.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSinkSpecAwsAuthSecretRef.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSinkSpecAwsAuthSecretRef."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["IntegrationSinkSpecAwsAuthSecretRef", Builder]:
        return GenericListBuilder[
            IntegrationSinkSpecAwsAuthSecretRef,
            IntegrationSinkSpecAwsAuthSecretRef.Builder,
        ]()

    name: str
    "Secret name"


class IntegrationSinkStatusAddress(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSinkStatusAddress"]:
            return IntegrationSinkStatusAddress

        def build(self) -> "IntegrationSinkStatusAddress":
            return IntegrationSinkStatusAddress(**self._attrs)

        def name(self, value: str | None, /) -> Self:
            return self._set("name", value)

        def url(self, value: str | None, /) -> Self:
            return self._set("url", value)

        def ca_certs(self, value: str | None, /) -> Self:
            return self._set("ca_certs", value)

        def audience(self, value: str | None, /) -> Self:
            return self._set("audience", value)

    class BuilderContext(BuilderContextBase["IntegrationSinkStatusAddress.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSinkStatusAddress.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSinkStatusAddress."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["IntegrationSinkStatusAddress", Builder]:
        return GenericListBuilder[
            IntegrationSinkStatusAddress, IntegrationSinkStatusAddress.Builder
        ]()

    name: str | None = None
    url: str | None = None
    ca_certs: Annotated[str | None, Field(alias="CACerts")] = None
    audience: str | None = None


class IntegrationSinkStatusAddressesItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSinkStatusAddressesItem"]:
            return IntegrationSinkStatusAddressesItem

        def build(self) -> "IntegrationSinkStatusAddressesItem":
            return IntegrationSinkStatusAddressesItem(**self._attrs)

        def name(self, value: str | None, /) -> Self:
            return self._set("name", value)

        def url(self, value: str | None, /) -> Self:
            return self._set("url", value)

        def ca_certs(self, value: str | None, /) -> Self:
            return self._set("ca_certs", value)

        def audience(self, value: str | None, /) -> Self:
            return self._set("audience", value)

    class BuilderContext(BuilderContextBase["IntegrationSinkStatusAddressesItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSinkStatusAddressesItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSinkStatusAddressesItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["IntegrationSinkStatusAddressesItem", Builder]:
        return GenericListBuilder[
            IntegrationSinkStatusAddressesItem,
            IntegrationSinkStatusAddressesItem.Builder,
        ]()

    name: str | None = None
    url: str | None = None
    ca_certs: Annotated[str | None, Field(alias="CACerts")] = None
    audience: str | None = None


class IntegrationSinkStatusPoliciesItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSinkStatusPoliciesItem"]:
            return IntegrationSinkStatusPoliciesItem

        def build(self) -> "IntegrationSinkStatusPoliciesItem":
            return IntegrationSinkStatusPoliciesItem(**self._attrs)

        def api_version(self, value: str | None, /) -> Self:
            "The API version of the applied EventPolicy. This indicates, which version of EventPolicy is supported by the resource."
            return self._set("api_version", value)

        def name(self, value: str | None, /) -> Self:
            "The name of the applied EventPolicy"
            return self._set("name", value)

    class BuilderContext(BuilderContextBase["IntegrationSinkStatusPoliciesItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSinkStatusPoliciesItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSinkStatusPoliciesItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["IntegrationSinkStatusPoliciesItem", Builder]:
        return GenericListBuilder[
            IntegrationSinkStatusPoliciesItem, IntegrationSinkStatusPoliciesItem.Builder
        ]()

    api_version: Annotated[str | None, Field(alias="apiVersion")] = None
    "The API version of the applied EventPolicy. This indicates, which version of EventPolicy is supported by the resource."
    name: str | None = None
    "The name of the applied EventPolicy"


class IntegrationSinkStatusConditionsItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSinkStatusConditionsItem"]:
            return IntegrationSinkStatusConditionsItem

        def build(self) -> "IntegrationSinkStatusConditionsItem":
            return IntegrationSinkStatusConditionsItem(**self._attrs)

        def last_transition_time(self, value: str | None, /) -> Self:
            "LastTransitionTime is the last time the condition transitioned from one status to another. We use VolatileTime in place of metav1.Time to exclude this from creating equality.Semantic differences (all other things held constant)."
            return self._set("last_transition_time", value)

        def message(self, value: str | None, /) -> Self:
            "A human readable message indicating details about the transition."
            return self._set("message", value)

        def reason(self, value: str | None, /) -> Self:
            "The reason for the condition\u0027s last transition."
            return self._set("reason", value)

        def severity(self, value: str | None, /) -> Self:
            "Severity with which to treat failures of this type of condition. When this is not specified, it defaults to Error."
            return self._set("severity", value)

        def status(self, value: str, /) -> Self:
            "Status of the condition, one of True, False, Unknown."
            return self._set("status", value)

        def type(self, value: str, /) -> Self:
            "Type of condition."
            return self._set("type", value)

    class BuilderContext(BuilderContextBase["IntegrationSinkStatusConditionsItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSinkStatusConditionsItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSinkStatusConditionsItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["IntegrationSinkStatusConditionsItem", Builder]:
        return GenericListBuilder[
            IntegrationSinkStatusConditionsItem,
            IntegrationSinkStatusConditionsItem.Builder,
        ]()

    last_transition_time: Annotated[str | None, Field(alias="lastTransitionTime")] = None
    "LastTransitionTime is the last time the condition transitioned from one status to another. We use VolatileTime in place of metav1.Time to exclude this from creating equality.Semantic differences (all other things held constant)."
    message: str | None = None
    "A human readable message indicating details about the transition."
    reason: str | None = None
    "The reason for the condition\u0027s last transition."
    severity: str | None = None
    "Severity with which to treat failures of this type of condition. When this is not specified, it defaults to Error."
    status: str
    "Status of the condition, one of True, False, Unknown."
    type: str
    "Type of condition."


class JobSinkStatusAddress(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["JobSinkStatusAddress"]:
            return JobSinkStatusAddress

        def build(self) -> "JobSinkStatusAddress":
            return JobSinkStatusAddress(**self._attrs)

        def name(self, value: str | None, /) -> Self:
            return self._set("name", value)

        def url(self, value: str | None, /) -> Self:
            return self._set("url", value)

        def ca_certs(self, value: str | None, /) -> Self:
            return self._set("ca_certs", value)

        def audience(self, value: str | None, /) -> Self:
            return self._set("audience", value)

    class BuilderContext(BuilderContextBase["JobSinkStatusAddress.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = JobSinkStatusAddress.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for JobSinkStatusAddress."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["JobSinkStatusAddress", Builder]:
        return GenericListBuilder[JobSinkStatusAddress, JobSinkStatusAddress.Builder]()

    name: str | None = None
    url: str | None = None
    ca_certs: Annotated[str | None, Field(alias="CACerts")] = None
    audience: str | None = None


class JobSinkStatusAddressesItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["JobSinkStatusAddressesItem"]:
            return JobSinkStatusAddressesItem

        def build(self) -> "JobSinkStatusAddressesItem":
            return JobSinkStatusAddressesItem(**self._attrs)

        def name(self, value: str | None, /) -> Self:
            return self._set("name", value)

        def url(self, value: str | None, /) -> Self:
            return self._set("url", value)

        def ca_certs(self, value: str | None, /) -> Self:
            return self._set("ca_certs", value)

        def audience(self, value: str | None, /) -> Self:
            return self._set("audience", value)

    class BuilderContext(BuilderContextBase["JobSinkStatusAddressesItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = JobSinkStatusAddressesItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for JobSinkStatusAddressesItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["JobSinkStatusAddressesItem", Builder]:
        return GenericListBuilder[JobSinkStatusAddressesItem, JobSinkStatusAddressesItem.Builder]()

    name: str | None = None
    url: str | None = None
    ca_certs: Annotated[str | None, Field(alias="CACerts")] = None
    audience: str | None = None


class JobSinkStatusJob(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["JobSinkStatusJob"]:
            return JobSinkStatusJob

        def build(self) -> "JobSinkStatusJob":
            return JobSinkStatusJob(**self._attrs)

        def selector(self, value: str | None, /) -> Self:
            "Label selector for all scheduled jobs"
            return self._set("selector", value)

    class BuilderContext(BuilderContextBase["JobSinkStatusJob.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = JobSinkStatusJob.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for JobSinkStatusJob."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["JobSinkStatusJob", Builder]:
        return GenericListBuilder[JobSinkStatusJob, JobSinkStatusJob.Builder]()

    selector: str | None = None
    "Label selector for all scheduled jobs"


class JobSinkStatusPoliciesItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["JobSinkStatusPoliciesItem"]:
            return JobSinkStatusPoliciesItem

        def build(self) -> "JobSinkStatusPoliciesItem":
            return JobSinkStatusPoliciesItem(**self._attrs)

        def api_version(self, value: str | None, /) -> Self:
            "The API version of the applied EventPolicy. This indicates, which version of EventPolicy is supported by the resource."
            return self._set("api_version", value)

        def name(self, value: str | None, /) -> Self:
            "The name of the applied EventPolicy"
            return self._set("name", value)

    class BuilderContext(BuilderContextBase["JobSinkStatusPoliciesItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = JobSinkStatusPoliciesItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for JobSinkStatusPoliciesItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["JobSinkStatusPoliciesItem", Builder]:
        return GenericListBuilder[JobSinkStatusPoliciesItem, JobSinkStatusPoliciesItem.Builder]()

    api_version: Annotated[str | None, Field(alias="apiVersion")] = None
    "The API version of the applied EventPolicy. This indicates, which version of EventPolicy is supported by the resource."
    name: str | None = None
    "The name of the applied EventPolicy"


class JobSinkStatusConditionsItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["JobSinkStatusConditionsItem"]:
            return JobSinkStatusConditionsItem

        def build(self) -> "JobSinkStatusConditionsItem":
            return JobSinkStatusConditionsItem(**self._attrs)

        def last_transition_time(self, value: str | None, /) -> Self:
            "LastTransitionTime is the last time the condition transitioned from one status to another. We use VolatileTime in place of metav1.Time to exclude this from creating equality.Semantic differences (all other things held constant)."
            return self._set("last_transition_time", value)

        def message(self, value: str | None, /) -> Self:
            "A human readable message indicating details about the transition."
            return self._set("message", value)

        def reason(self, value: str | None, /) -> Self:
            "The reason for the condition\u0027s last transition."
            return self._set("reason", value)

        def severity(self, value: str | None, /) -> Self:
            "Severity with which to treat failures of this type of condition. When this is not specified, it defaults to Error."
            return self._set("severity", value)

        def status(self, value: str, /) -> Self:
            "Status of the condition, one of True, False, Unknown."
            return self._set("status", value)

        def type(self, value: str, /) -> Self:
            "Type of condition."
            return self._set("type", value)

    class BuilderContext(BuilderContextBase["JobSinkStatusConditionsItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = JobSinkStatusConditionsItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for JobSinkStatusConditionsItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["JobSinkStatusConditionsItem", Builder]:
        return GenericListBuilder[
            JobSinkStatusConditionsItem, JobSinkStatusConditionsItem.Builder
        ]()

    last_transition_time: Annotated[str | None, Field(alias="lastTransitionTime")] = None
    "LastTransitionTime is the last time the condition transitioned from one status to another. We use VolatileTime in place of metav1.Time to exclude this from creating equality.Semantic differences (all other things held constant)."
    message: str | None = None
    "A human readable message indicating details about the transition."
    reason: str | None = None
    "The reason for the condition\u0027s last transition."
    severity: str | None = None
    "Severity with which to treat failures of this type of condition. When this is not specified, it defaults to Error."
    status: str
    "Status of the condition, one of True, False, Unknown."
    type: str
    "Type of condition."


class IntegrationSinkStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSinkStatus"]:
            return IntegrationSinkStatus

        def build(self) -> "IntegrationSinkStatus":
            return IntegrationSinkStatus(**self._attrs)

        @overload
        def address(
            self, value_or_callback: IntegrationSinkStatusAddress | None, /
        ) -> "IntegrationSinkStatus.Builder": ...

        @overload
        def address(
            self,
            value_or_callback: Callable[
                [IntegrationSinkStatusAddress.Builder],
                IntegrationSinkStatusAddress.Builder | IntegrationSinkStatusAddress,
            ],
            /,
        ) -> "IntegrationSinkStatus.Builder": ...

        @overload
        def address(
            self, value_or_callback: Never = ...
        ) -> "IntegrationSinkStatusAddress.BuilderContext": ...

        def address(self, value_or_callback=UNSET, /):
            "IntegrationSink is Addressable. It exposes the endpoints as URIs to get events delivered into the used Kamelet."
            if self._in_context and value_or_callback is UNSET:
                context = IntegrationSinkStatusAddress.BuilderContext()
                context._parent_builder = self
                context._field_name = "address"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntegrationSinkStatusAddress.builder())
                if isinstance(output, IntegrationSinkStatusAddress.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("address", value)

        @overload
        def addresses(
            self, value_or_callback: list[IntegrationSinkStatusAddressesItem] | None, /
        ) -> "IntegrationSinkStatus.Builder": ...

        @overload
        def addresses(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        IntegrationSinkStatusAddressesItem,
                        IntegrationSinkStatusAddressesItem.Builder,
                    ]
                ],
                GenericListBuilder[
                    IntegrationSinkStatusAddressesItem,
                    IntegrationSinkStatusAddressesItem.Builder,
                ]
                | list[IntegrationSinkStatusAddressesItem],
            ],
            /,
        ) -> "IntegrationSinkStatus.Builder": ...

        @overload
        def addresses(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[IntegrationSinkStatusAddressesItem.Builder]: ...

        def addresses(self, value_or_callback=UNSET, /):
            "IntegrationSink is Addressable. It exposes the endpoints as URIs to get events delivered into the used Kamelet."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[IntegrationSinkStatusAddressesItem.Builder]()
                context._parent_builder = self
                context._field_name = "addresses"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntegrationSinkStatusAddressesItem.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("addresses", value)

        def annotations(self, value: dict[str, Any] | None, /) -> Self:
            "Annotations is additional Status fields for the Resource to save some additional State as well as convey more information to the user. This is roughly akin to Annotations on any k8s resource, just the reconciler conveying richer information outwards."
            return self._set("annotations", value)

        @overload
        def policies(
            self, value_or_callback: list[IntegrationSinkStatusPoliciesItem] | None, /
        ) -> "IntegrationSinkStatus.Builder": ...

        @overload
        def policies(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        IntegrationSinkStatusPoliciesItem,
                        IntegrationSinkStatusPoliciesItem.Builder,
                    ]
                ],
                GenericListBuilder[
                    IntegrationSinkStatusPoliciesItem,
                    IntegrationSinkStatusPoliciesItem.Builder,
                ]
                | list[IntegrationSinkStatusPoliciesItem],
            ],
            /,
        ) -> "IntegrationSinkStatus.Builder": ...

        @overload
        def policies(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[IntegrationSinkStatusPoliciesItem.Builder]: ...

        def policies(self, value_or_callback=UNSET, /):
            "List of applied EventPolicies"
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[IntegrationSinkStatusPoliciesItem.Builder]()
                context._parent_builder = self
                context._field_name = "policies"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntegrationSinkStatusPoliciesItem.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("policies", value)

        @overload
        def conditions(
            self, value_or_callback: list[IntegrationSinkStatusConditionsItem] | None, /
        ) -> "IntegrationSinkStatus.Builder": ...

        @overload
        def conditions(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        IntegrationSinkStatusConditionsItem,
                        IntegrationSinkStatusConditionsItem.Builder,
                    ]
                ],
                GenericListBuilder[
                    IntegrationSinkStatusConditionsItem,
                    IntegrationSinkStatusConditionsItem.Builder,
                ]
                | list[IntegrationSinkStatusConditionsItem],
            ],
            /,
        ) -> "IntegrationSinkStatus.Builder": ...

        @overload
        def conditions(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[IntegrationSinkStatusConditionsItem.Builder]: ...

        def conditions(self, value_or_callback=UNSET, /):
            "Conditions the latest available observations of a resource\u0027s current state."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[IntegrationSinkStatusConditionsItem.Builder]()
                context._parent_builder = self
                context._field_name = "conditions"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntegrationSinkStatusConditionsItem.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("conditions", value)

        def observed_generation(self, value: int | None, /) -> Self:
            "ObservedGeneration is the \u0027Generation\u0027 of the Service that was last processed by the controller."
            return self._set("observed_generation", value)

    class BuilderContext(BuilderContextBase["IntegrationSinkStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSinkStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSinkStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["IntegrationSinkStatus", Builder]:
        return GenericListBuilder[IntegrationSinkStatus, IntegrationSinkStatus.Builder]()

    address: IntegrationSinkStatusAddress | None = None
    "IntegrationSink is Addressable. It exposes the endpoints as URIs to get events delivered into the used Kamelet."
    addresses: list[IntegrationSinkStatusAddressesItem] | None = None
    "IntegrationSink is Addressable. It exposes the endpoints as URIs to get events delivered into the used Kamelet."
    annotations: dict[str, Any] | None = None
    "Annotations is additional Status fields for the Resource to save some additional State as well as convey more information to the user. This is roughly akin to Annotations on any k8s resource, just the reconciler conveying richer information outwards."
    policies: list[IntegrationSinkStatusPoliciesItem] | None = None
    "List of applied EventPolicies"
    conditions: list[IntegrationSinkStatusConditionsItem] | None = None
    "Conditions the latest available observations of a resource\u0027s current state."
    observed_generation: Annotated[int | None, Field(alias="observedGeneration")] = None
    "ObservedGeneration is the \u0027Generation\u0027 of the Service that was last processed by the controller."


class JobSinkStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["JobSinkStatus"]:
            return JobSinkStatus

        def build(self) -> "JobSinkStatus":
            return JobSinkStatus(**self._attrs)

        @overload
        def address(
            self, value_or_callback: JobSinkStatusAddress | None, /
        ) -> "JobSinkStatus.Builder": ...

        @overload
        def address(
            self,
            value_or_callback: Callable[
                [JobSinkStatusAddress.Builder],
                JobSinkStatusAddress.Builder | JobSinkStatusAddress,
            ],
            /,
        ) -> "JobSinkStatus.Builder": ...

        @overload
        def address(
            self, value_or_callback: Never = ...
        ) -> "JobSinkStatusAddress.BuilderContext": ...

        def address(self, value_or_callback=UNSET, /):
            "JobSink is Addressable. It exposes the endpoint as an URI to schedule long running jobs when an even occurs."
            if self._in_context and value_or_callback is UNSET:
                context = JobSinkStatusAddress.BuilderContext()
                context._parent_builder = self
                context._field_name = "address"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(JobSinkStatusAddress.builder())
                if isinstance(output, JobSinkStatusAddress.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("address", value)

        @overload
        def addresses(
            self, value_or_callback: list[JobSinkStatusAddressesItem] | None, /
        ) -> "JobSinkStatus.Builder": ...

        @overload
        def addresses(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        JobSinkStatusAddressesItem, JobSinkStatusAddressesItem.Builder
                    ]
                ],
                GenericListBuilder[JobSinkStatusAddressesItem, JobSinkStatusAddressesItem.Builder]
                | list[JobSinkStatusAddressesItem],
            ],
            /,
        ) -> "JobSinkStatus.Builder": ...

        @overload
        def addresses(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[JobSinkStatusAddressesItem.Builder]: ...

        def addresses(self, value_or_callback=UNSET, /):
            "JobSink is Addressable. It exposes the endpoint as an URI to schedule long running jobs when an even occurs."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[JobSinkStatusAddressesItem.Builder]()
                context._parent_builder = self
                context._field_name = "addresses"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(JobSinkStatusAddressesItem.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("addresses", value)

        @overload
        def job(self, value_or_callback: JobSinkStatusJob | None, /) -> "JobSinkStatus.Builder": ...

        @overload
        def job(
            self,
            value_or_callback: Callable[
                [JobSinkStatusJob.Builder], JobSinkStatusJob.Builder | JobSinkStatusJob
            ],
            /,
        ) -> "JobSinkStatus.Builder": ...

        @overload
        def job(self, value_or_callback: Never = ...) -> "JobSinkStatusJob.BuilderContext": ...

        def job(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = JobSinkStatusJob.BuilderContext()
                context._parent_builder = self
                context._field_name = "job"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(JobSinkStatusJob.builder())
                if isinstance(output, JobSinkStatusJob.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("job", value)

        def annotations(self, value: dict[str, Any] | None, /) -> Self:
            "Annotations is additional Status fields for the Resource to save some additional State as well as convey more information to the user. This is roughly akin to Annotations on any k8s resource, just the reconciler conveying richer information outwards."
            return self._set("annotations", value)

        @overload
        def policies(
            self, value_or_callback: list[JobSinkStatusPoliciesItem] | None, /
        ) -> "JobSinkStatus.Builder": ...

        @overload
        def policies(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[JobSinkStatusPoliciesItem, JobSinkStatusPoliciesItem.Builder]],
                GenericListBuilder[JobSinkStatusPoliciesItem, JobSinkStatusPoliciesItem.Builder]
                | list[JobSinkStatusPoliciesItem],
            ],
            /,
        ) -> "JobSinkStatus.Builder": ...

        @overload
        def policies(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[JobSinkStatusPoliciesItem.Builder]: ...

        def policies(self, value_or_callback=UNSET, /):
            "List of applied EventPolicies"
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[JobSinkStatusPoliciesItem.Builder]()
                context._parent_builder = self
                context._field_name = "policies"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(JobSinkStatusPoliciesItem.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("policies", value)

        @overload
        def conditions(
            self, value_or_callback: list[JobSinkStatusConditionsItem] | None, /
        ) -> "JobSinkStatus.Builder": ...

        @overload
        def conditions(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        JobSinkStatusConditionsItem, JobSinkStatusConditionsItem.Builder
                    ]
                ],
                GenericListBuilder[JobSinkStatusConditionsItem, JobSinkStatusConditionsItem.Builder]
                | list[JobSinkStatusConditionsItem],
            ],
            /,
        ) -> "JobSinkStatus.Builder": ...

        @overload
        def conditions(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[JobSinkStatusConditionsItem.Builder]: ...

        def conditions(self, value_or_callback=UNSET, /):
            "Conditions the latest available observations of a resource\u0027s current state."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[JobSinkStatusConditionsItem.Builder]()
                context._parent_builder = self
                context._field_name = "conditions"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(JobSinkStatusConditionsItem.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("conditions", value)

        def observed_generation(self, value: int | None, /) -> Self:
            "ObservedGeneration is the \u0027Generation\u0027 of the Service that was last processed by the controller."
            return self._set("observed_generation", value)

    class BuilderContext(BuilderContextBase["JobSinkStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = JobSinkStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for JobSinkStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["JobSinkStatus", Builder]:
        return GenericListBuilder[JobSinkStatus, JobSinkStatus.Builder]()

    address: JobSinkStatusAddress | None = None
    "JobSink is Addressable. It exposes the endpoint as an URI to schedule long running jobs when an even occurs."
    addresses: list[JobSinkStatusAddressesItem] | None = None
    "JobSink is Addressable. It exposes the endpoint as an URI to schedule long running jobs when an even occurs."
    job: JobSinkStatusJob | None = None
    annotations: dict[str, Any] | None = None
    "Annotations is additional Status fields for the Resource to save some additional State as well as convey more information to the user. This is roughly akin to Annotations on any k8s resource, just the reconciler conveying richer information outwards."
    policies: list[JobSinkStatusPoliciesItem] | None = None
    "List of applied EventPolicies"
    conditions: list[JobSinkStatusConditionsItem] | None = None
    "Conditions the latest available observations of a resource\u0027s current state."
    observed_generation: Annotated[int | None, Field(alias="observedGeneration")] = None
    "ObservedGeneration is the \u0027Generation\u0027 of the Service that was last processed by the controller."


class IntegrationSinkSpecAwsAuthSecret(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSinkSpecAwsAuthSecret"]:
            return IntegrationSinkSpecAwsAuthSecret

        def build(self) -> "IntegrationSinkSpecAwsAuthSecret":
            return IntegrationSinkSpecAwsAuthSecret(**self._attrs)

        @overload
        def ref(
            self, value_or_callback: IntegrationSinkSpecAwsAuthSecretRef | None, /
        ) -> "IntegrationSinkSpecAwsAuthSecret.Builder": ...

        @overload
        def ref(
            self,
            value_or_callback: Callable[
                [IntegrationSinkSpecAwsAuthSecretRef.Builder],
                IntegrationSinkSpecAwsAuthSecretRef.Builder | IntegrationSinkSpecAwsAuthSecretRef,
            ],
            /,
        ) -> "IntegrationSinkSpecAwsAuthSecret.Builder": ...

        @overload
        def ref(
            self, value_or_callback: Never = ...
        ) -> "IntegrationSinkSpecAwsAuthSecretRef.BuilderContext": ...

        def ref(self, value_or_callback=UNSET, /):
            "Secret reference.\n"
            if self._in_context and value_or_callback is UNSET:
                context = IntegrationSinkSpecAwsAuthSecretRef.BuilderContext()
                context._parent_builder = self
                context._field_name = "ref"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntegrationSinkSpecAwsAuthSecretRef.builder())
                if isinstance(output, IntegrationSinkSpecAwsAuthSecretRef.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("ref", value)

    class BuilderContext(BuilderContextBase["IntegrationSinkSpecAwsAuthSecret.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSinkSpecAwsAuthSecret.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSinkSpecAwsAuthSecret."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["IntegrationSinkSpecAwsAuthSecret", Builder]:
        return GenericListBuilder[
            IntegrationSinkSpecAwsAuthSecret, IntegrationSinkSpecAwsAuthSecret.Builder
        ]()

    ref: IntegrationSinkSpecAwsAuthSecretRef | None = None
    "Secret reference.\n"


class JobSink(Resource):
    __cloudcoil_api__: ClassVar[dict] = {
        "plural": "jobsinks",
        "scope": "Namespaced",
        "status": True,
    }

    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["JobSink"]:
            return JobSink

        def build(self) -> "JobSink":
            return JobSink(**self._attrs)

        @overload
        def spec(self, value_or_callback: JobSinkSpec | None, /) -> "JobSink.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[[JobSinkSpec.Builder], JobSinkSpec.Builder | JobSinkSpec],
            /,
        ) -> "JobSink.Builder": ...

        @overload
        def spec(self, value_or_callback: Never = ...) -> "JobSinkSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = JobSinkSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(JobSinkSpec.builder())
                if isinstance(output, JobSinkSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

        @overload
        def status(self, value_or_callback: JobSinkStatus | None, /) -> "JobSink.Builder": ...

        @overload
        def status(
            self,
            value_or_callback: Callable[
                [JobSinkStatus.Builder], JobSinkStatus.Builder | JobSinkStatus
            ],
            /,
        ) -> "JobSink.Builder": ...

        @overload
        def status(self, value_or_callback: Never = ...) -> "JobSinkStatus.BuilderContext": ...

        def status(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = JobSinkStatus.BuilderContext()
                context._parent_builder = self
                context._field_name = "status"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(JobSinkStatus.builder())
                if isinstance(output, JobSinkStatus.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("status", value)

        def api_version(self, value: Literal["sinks.knative.dev/v1alpha1"], /) -> Self:
            return self._set("api_version", value)

        def kind(self, value: Literal["JobSink"], /) -> Self:
            return self._set("kind", value)

        @overload
        def metadata(self, value_or_callback: ObjectMeta | None, /) -> "JobSink.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "JobSink.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

    class BuilderContext(BuilderContextBase["JobSink.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = JobSink.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for JobSink."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["JobSink", Builder]:
        return GenericListBuilder[JobSink, JobSink.Builder]()

    spec: JobSinkSpec | None = None
    status: JobSinkStatus | None = None
    api_version: Annotated[Literal["sinks.knative.dev/v1alpha1"], Field(alias="apiVersion")] = (
        "sinks.knative.dev/v1alpha1"
    )
    kind: Literal["JobSink"] = "JobSink"
    metadata: ObjectMeta | None = None


class IntegrationSinkSpecAwsAuth(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSinkSpecAwsAuth"]:
            return IntegrationSinkSpecAwsAuth

        def build(self) -> "IntegrationSinkSpecAwsAuth":
            return IntegrationSinkSpecAwsAuth(**self._attrs)

        @overload
        def secret(
            self, value_or_callback: IntegrationSinkSpecAwsAuthSecret | None, /
        ) -> "IntegrationSinkSpecAwsAuth.Builder": ...

        @overload
        def secret(
            self,
            value_or_callback: Callable[
                [IntegrationSinkSpecAwsAuthSecret.Builder],
                IntegrationSinkSpecAwsAuthSecret.Builder | IntegrationSinkSpecAwsAuthSecret,
            ],
            /,
        ) -> "IntegrationSinkSpecAwsAuth.Builder": ...

        @overload
        def secret(
            self, value_or_callback: Never = ...
        ) -> "IntegrationSinkSpecAwsAuthSecret.BuilderContext": ...

        def secret(self, value_or_callback=UNSET, /):
            "Auth secret"
            if self._in_context and value_or_callback is UNSET:
                context = IntegrationSinkSpecAwsAuthSecret.BuilderContext()
                context._parent_builder = self
                context._field_name = "secret"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntegrationSinkSpecAwsAuthSecret.builder())
                if isinstance(output, IntegrationSinkSpecAwsAuthSecret.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("secret", value)

        def service_account_name(self, value: str | None, /) -> Self:
            "Optional ServiceAccount to assign to pod. This enables the pod default credentials to be used instead of the auth secret."
            return self._set("service_account_name", value)

    class BuilderContext(BuilderContextBase["IntegrationSinkSpecAwsAuth.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSinkSpecAwsAuth.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSinkSpecAwsAuth."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["IntegrationSinkSpecAwsAuth", Builder]:
        return GenericListBuilder[IntegrationSinkSpecAwsAuth, IntegrationSinkSpecAwsAuth.Builder]()

    secret: IntegrationSinkSpecAwsAuthSecret | None = None
    "Auth secret"
    service_account_name: Annotated[str | None, Field(alias="serviceAccountName")] = None
    "Optional ServiceAccount to assign to pod. This enables the pod default credentials to be used instead of the auth secret."


class IntegrationSinkSpecAws(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSinkSpecAws"]:
            return IntegrationSinkSpecAws

        def build(self) -> "IntegrationSinkSpecAws":
            return IntegrationSinkSpecAws(**self._attrs)

        @overload
        def s3(
            self, value_or_callback: IntegrationSinkSpecAwsS3 | None, /
        ) -> "IntegrationSinkSpecAws.Builder": ...

        @overload
        def s3(
            self,
            value_or_callback: Callable[
                [IntegrationSinkSpecAwsS3.Builder],
                IntegrationSinkSpecAwsS3.Builder | IntegrationSinkSpecAwsS3,
            ],
            /,
        ) -> "IntegrationSinkSpecAws.Builder": ...

        @overload
        def s3(
            self, value_or_callback: Never = ...
        ) -> "IntegrationSinkSpecAwsS3.BuilderContext": ...

        def s3(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = IntegrationSinkSpecAwsS3.BuilderContext()
                context._parent_builder = self
                context._field_name = "s3"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntegrationSinkSpecAwsS3.builder())
                if isinstance(output, IntegrationSinkSpecAwsS3.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("s3", value)

        @overload
        def sqs(
            self, value_or_callback: IntegrationSinkSpecAwsSqs | None, /
        ) -> "IntegrationSinkSpecAws.Builder": ...

        @overload
        def sqs(
            self,
            value_or_callback: Callable[
                [IntegrationSinkSpecAwsSqs.Builder],
                IntegrationSinkSpecAwsSqs.Builder | IntegrationSinkSpecAwsSqs,
            ],
            /,
        ) -> "IntegrationSinkSpecAws.Builder": ...

        @overload
        def sqs(
            self, value_or_callback: Never = ...
        ) -> "IntegrationSinkSpecAwsSqs.BuilderContext": ...

        def sqs(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = IntegrationSinkSpecAwsSqs.BuilderContext()
                context._parent_builder = self
                context._field_name = "sqs"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntegrationSinkSpecAwsSqs.builder())
                if isinstance(output, IntegrationSinkSpecAwsSqs.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("sqs", value)

        @overload
        def sns(
            self, value_or_callback: IntegrationSinkSpecAwsSns | None, /
        ) -> "IntegrationSinkSpecAws.Builder": ...

        @overload
        def sns(
            self,
            value_or_callback: Callable[
                [IntegrationSinkSpecAwsSns.Builder],
                IntegrationSinkSpecAwsSns.Builder | IntegrationSinkSpecAwsSns,
            ],
            /,
        ) -> "IntegrationSinkSpecAws.Builder": ...

        @overload
        def sns(
            self, value_or_callback: Never = ...
        ) -> "IntegrationSinkSpecAwsSns.BuilderContext": ...

        def sns(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = IntegrationSinkSpecAwsSns.BuilderContext()
                context._parent_builder = self
                context._field_name = "sns"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntegrationSinkSpecAwsSns.builder())
                if isinstance(output, IntegrationSinkSpecAwsSns.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("sns", value)

        @overload
        def auth(
            self, value_or_callback: IntegrationSinkSpecAwsAuth | None, /
        ) -> "IntegrationSinkSpecAws.Builder": ...

        @overload
        def auth(
            self,
            value_or_callback: Callable[
                [IntegrationSinkSpecAwsAuth.Builder],
                IntegrationSinkSpecAwsAuth.Builder | IntegrationSinkSpecAwsAuth,
            ],
            /,
        ) -> "IntegrationSinkSpecAws.Builder": ...

        @overload
        def auth(
            self, value_or_callback: Never = ...
        ) -> "IntegrationSinkSpecAwsAuth.BuilderContext": ...

        def auth(self, value_or_callback=UNSET, /):
            "Auth configurations"
            if self._in_context and value_or_callback is UNSET:
                context = IntegrationSinkSpecAwsAuth.BuilderContext()
                context._parent_builder = self
                context._field_name = "auth"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntegrationSinkSpecAwsAuth.builder())
                if isinstance(output, IntegrationSinkSpecAwsAuth.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("auth", value)

    class BuilderContext(BuilderContextBase["IntegrationSinkSpecAws.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSinkSpecAws.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSinkSpecAws."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["IntegrationSinkSpecAws", Builder]:
        return GenericListBuilder[IntegrationSinkSpecAws, IntegrationSinkSpecAws.Builder]()

    s3: IntegrationSinkSpecAwsS3 | None = None
    sqs: IntegrationSinkSpecAwsSqs | None = None
    sns: IntegrationSinkSpecAwsSns | None = None
    auth: IntegrationSinkSpecAwsAuth | None = None
    "Auth configurations"


class IntegrationSinkSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSinkSpec"]:
            return IntegrationSinkSpec

        def build(self) -> "IntegrationSinkSpec":
            return IntegrationSinkSpec(**self._attrs)

        @overload
        def log(
            self, value_or_callback: IntegrationSinkSpecLog | None, /
        ) -> "IntegrationSinkSpec.Builder": ...

        @overload
        def log(
            self,
            value_or_callback: Callable[
                [IntegrationSinkSpecLog.Builder],
                IntegrationSinkSpecLog.Builder | IntegrationSinkSpecLog,
            ],
            /,
        ) -> "IntegrationSinkSpec.Builder": ...

        @overload
        def log(
            self, value_or_callback: Never = ...
        ) -> "IntegrationSinkSpecLog.BuilderContext": ...

        def log(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = IntegrationSinkSpecLog.BuilderContext()
                context._parent_builder = self
                context._field_name = "log"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntegrationSinkSpecLog.builder())
                if isinstance(output, IntegrationSinkSpecLog.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("log", value)

        @overload
        def aws(
            self, value_or_callback: IntegrationSinkSpecAws | None, /
        ) -> "IntegrationSinkSpec.Builder": ...

        @overload
        def aws(
            self,
            value_or_callback: Callable[
                [IntegrationSinkSpecAws.Builder],
                IntegrationSinkSpecAws.Builder | IntegrationSinkSpecAws,
            ],
            /,
        ) -> "IntegrationSinkSpec.Builder": ...

        @overload
        def aws(
            self, value_or_callback: Never = ...
        ) -> "IntegrationSinkSpecAws.BuilderContext": ...

        def aws(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = IntegrationSinkSpecAws.BuilderContext()
                context._parent_builder = self
                context._field_name = "aws"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntegrationSinkSpecAws.builder())
                if isinstance(output, IntegrationSinkSpecAws.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("aws", value)

    class BuilderContext(BuilderContextBase["IntegrationSinkSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSinkSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSinkSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["IntegrationSinkSpec", Builder]:
        return GenericListBuilder[IntegrationSinkSpec, IntegrationSinkSpec.Builder]()

    log: IntegrationSinkSpecLog | None = None
    aws: IntegrationSinkSpecAws | None = None


class IntegrationSink(Resource):
    __cloudcoil_api__: ClassVar[dict] = {
        "plural": "integrationsinks",
        "scope": "Namespaced",
        "status": True,
    }

    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["IntegrationSink"]:
            return IntegrationSink

        def build(self) -> "IntegrationSink":
            return IntegrationSink(**self._attrs)

        @overload
        def spec(
            self, value_or_callback: IntegrationSinkSpec | None, /
        ) -> "IntegrationSink.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[
                [IntegrationSinkSpec.Builder],
                IntegrationSinkSpec.Builder | IntegrationSinkSpec,
            ],
            /,
        ) -> "IntegrationSink.Builder": ...

        @overload
        def spec(self, value_or_callback: Never = ...) -> "IntegrationSinkSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = IntegrationSinkSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntegrationSinkSpec.builder())
                if isinstance(output, IntegrationSinkSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

        @overload
        def status(
            self, value_or_callback: IntegrationSinkStatus | None, /
        ) -> "IntegrationSink.Builder": ...

        @overload
        def status(
            self,
            value_or_callback: Callable[
                [IntegrationSinkStatus.Builder],
                IntegrationSinkStatus.Builder | IntegrationSinkStatus,
            ],
            /,
        ) -> "IntegrationSink.Builder": ...

        @overload
        def status(
            self, value_or_callback: Never = ...
        ) -> "IntegrationSinkStatus.BuilderContext": ...

        def status(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = IntegrationSinkStatus.BuilderContext()
                context._parent_builder = self
                context._field_name = "status"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(IntegrationSinkStatus.builder())
                if isinstance(output, IntegrationSinkStatus.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("status", value)

        def api_version(self, value: Literal["sinks.knative.dev/v1alpha1"], /) -> Self:
            return self._set("api_version", value)

        def kind(self, value: Literal["IntegrationSink"], /) -> Self:
            return self._set("kind", value)

        @overload
        def metadata(
            self, value_or_callback: ObjectMeta | None, /
        ) -> "IntegrationSink.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "IntegrationSink.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

    class BuilderContext(BuilderContextBase["IntegrationSink.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = IntegrationSink.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for IntegrationSink."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["IntegrationSink", Builder]:
        return GenericListBuilder[IntegrationSink, IntegrationSink.Builder]()

    spec: IntegrationSinkSpec | None = None
    status: IntegrationSinkStatus | None = None
    api_version: Annotated[Literal["sinks.knative.dev/v1alpha1"], Field(alias="apiVersion")] = (
        "sinks.knative.dev/v1alpha1"
    )
    kind: Literal["IntegrationSink"] = "IntegrationSink"
    metadata: ObjectMeta | None = None
